// Copyright 2019 The GoPacket Authors. All rights reserved.
//
// Use of this source code is governed by a BSD-style license
// that can be found in the LICENSE file in the root of the source
// tree.

package layers

// code from https://github.com/google/gopacket/pull/733

type diameterVendor struct {
	vendorID   string
	vendorName string
}

type avpType struct {
	name   string
	format string
}

var diameterVendors = map[uint32]diameterVendor{
	0:     {"None", "None"},
	9:     {"Cisco", "Cisco Systems Inc."},
	11:    {"HP", "Hewlett Packard"},
	42:    {"Sun", "Sun Microsystems, Inc."},
	62:    {"Merit", "Merit Networks"},
	94:    {"Nokia", "Nokia"},
	161:   {"Motorola", "Motorola"},
	193:   {"Ericsson", "Ericsson"},
	311:   {"MS", "Microsoft Corporation"},
	429:   {"USR", "US Robotics Corp."},
	2352:  {"Redback", "Redback"},
	2636:  {"Juniper", "Juniper"},
	2637:  {"Nortel", ">Nortel Networks"},
	2937:  {"Deutsche_Telekom_AG", "Deutsche Telekom AG"},
	3199:  {"Shasta", ">Shasta"},
	3561:  {"DSLForum", ">DSL Forum"},
	4329:  {"Siemens", ">Siemens AG"},
	5535:  {"TGPP2", ">3rd Generation Partnership Project 2 (3GPP2)"},
	8164:  {"SN", ">Starent Networks"},
	9421:  {"VFD2", ">Vodafone D2"},
	10415: {"TGPP", ">3rd Generation Partnership Project (3GPP)"},
	10548: {"Netzwert", ">Netzwert AG"},
	10923: {"EriJun", ">Ericsson Juniper"},
	12645: {"Vodafone", "Vodafone"},
	12951: {"Verizon", ">Verizon Wireless Enterprise"},
	13019: {"ETSI", ">European Telecommunications Standards Institute"},
	13568: {"NeuStar", ">NeuStar"},
	14008: {"SICS", ">SICS Vendor"},
	14122: {"WFA", ">WiFi-Alliance"},
	15573: {"Apertio", ">Apertio Ltd."},
	24757: {"WiMAX", ">WiMAX Forum"},
	28458: {"NSN", ">Nokia Siemens Networks"},
	29168: {"TMO", ">T-Mobile International"},
}

var avpCodes = map[uint32]avpType{
	1:    {"User-Name", "UTF8String"},
	2:    {"User-Password", "OctetString"},
	3:    {"CHAP-Password", "OctetString"},
	4:    {"NAS-IP-Address", "OctetString"},
	5:    {"NAS-Port", "Unsigned32"},
	6:    {"Service-Type", "Enumerated"},
	7:    {"Framed-Protocol", "Enumerated"},
	8:    {"Framed-IP-Address", "IP"},
	9:    {"Framed-IP-Netmask", "IP"},
	10:   {"Framed-Routing", "Enumerated"},
	11:   {"Filter-Id", "UTF8String"},
	12:   {"Framed-MTU", "Unsigned32"},
	13:   {"Framed-Compression", "Enumerated"},
	14:   {"Login-IP-Host", "IPAddress"},
	15:   {"Login-Service", "Enumerated"},
	16:   {"Login-TCP-Port", "Unsigned32"},
	17:   {"Unassigned", "OctetString"},
	18:   {"Reply-Message", "UTF8String"},
	19:   {"Callback-Number", "UTF8String"},
	20:   {"Callback-Id", "UTF8String"},
	21:   {"Unassigned", "OctetString"},
	22:   {"Framed-Route", "UTF8String"},
	23:   {"Framed-IPX-Network", "UTF8String"},
	24:   {"State", "OctetString"},
	25:   {"Class", "OctetString"},
	26:   {"Vendor-Specific", "Unsigned32"},
	27:   {"Session-Timeout", "Unsigned32"},
	28:   {"Idle-Timeout", "Unsigned32"},
	29:   {"Termination-Action", "Unsigned32"},
	30:   {"Called-Station-Id", "UTF8String"},
	31:   {"Calling-Station-Id", "UTF8String"},
	32:   {"NAS-Identifier", "OctetString"},
	33:   {"Proxy-State", "OctetString"},
	34:   {"Login-LAT-Service", "OctetString"},
	35:   {"Login-LAT-Node", "OctetString"},
	36:   {"Login-LAT-Group", "OctetString"},
	37:   {"Framed-AppleTalk-Link", "Unsigned32"},
	38:   {"Framed-AppleTalk-Network", "Unsigned32"},
	39:   {"Framed-AppleTalk-Zone", "OctetString"},
	40:   {"Acct-Status-Type", "Unsigned32"},
	41:   {"Acct-Delay-Time", "Unsigned32"},
	42:   {"Acct-Input-Octets", "Unsigned32"},
	43:   {"Acct-Output-Octets", "Unsigned32"},
	44:   {"Acct-Session-Id", "OctetString"},
	45:   {"Acct-Authentic", "Enumerated"},
	46:   {"Acct-Session-Time", "Unsigned32"},
	47:   {"Acct-Input-Packets", "Integer32"},
	48:   {"Acct-Output-Packets", "Integer32"},
	49:   {"Acct-Terminate-Cause", "Unsigned32"},
	50:   {"Accounting-Multi-Session-Id", "OctetString"},
	51:   {"Acct-Link-Count", "Unsigned32"},
	52:   {"Acct-Input-Gigawords", "Integer32"},
	53:   {"Acct-Output-Gigawords", "Integer32"},
	54:   {"Unassigned", "OctetString"},
	55:   {"Event-Timestamp", "Time"},
	56:   {"Egress-VLANID", "OctetString"},
	57:   {"Ingress-Filters", "Enumerated"},
	58:   {"Egress-VLAN-Name", "UTF8String"},
	59:   {"User-Priority-Table", "OctetString"},
	60:   {"CHAP-Challenge", "OctetString"},
	61:   {"NAS-Port-Type", "Enumerated"},
	62:   {"Port-Limit", "Unsigned32"},
	63:   {"Login-LAT-Port", "OctetString"},
	64:   {"Tunnel-Type", "Enumerated"},
	65:   {"Tunnel-Medium-Type", "Enumerated"},
	66:   {"Acct-Tunnel-Client-Endpoint", "UTF8String"},
	67:   {"Tunnel-Server-Endpoint", "UTF8String"},
	68:   {"Acct-Tunnel-Connection-ID", "OctetString"},
	69:   {"Tunnel-Password", "OctetString"},
	70:   {"ARAP-Password", "OctetString"},
	71:   {"ARAP-Features", "OctetString"},
	72:   {"ARAP-Zone-Access", "Enumerated"},
	73:   {"ARAP-Security", "Unsigned32"},
	74:   {"ARAP-Security-Data", "OctetString"},
	75:   {"Password-Retry", "Unsigned32"},
	76:   {"Prompt", "Enumerated"},
	77:   {"Connect-Info", "UTF8String"},
	78:   {"Configuration-Token", "OctetString"},
	79:   {"EAP-Message", "OctetString"},
	80:   {"Signature", "OctetString"},
	81:   {"Tunnel-Private-Group-Id", "OctetString"},
	82:   {"Tunnel-Assignment-Id", "OctetString"},
	83:   {"Tunnel-Preference", "Unsigned32"},
	84:   {"ARAP-Challenge-Response", "OctetString"},
	85:   {"Acct-Interim-Interval", "Unsigned32"},
	86:   {"Acct-Tunnel-Packets-Lost", "Unsigned32"},
	87:   {"NAS-Port-Id", "UTF8String"},
	88:   {"Framed-Pool", "OctetString"},
	89:   {"CUI", "UTF8String"},
	90:   {"Tunnel-Client-Auth-Id", "UTF8String"},
	91:   {"Tunnel-Server-Auth-Id", "UTF8String"},
	93:   {"Unassigned", "OctetString"},
	94:   {"Originating-Line-Info", "OctetString"},
	95:   {"NAS-IPv6-Address", "OctetString"},
	96:   {"Framed-Interface-Id", "Unsigned64"},
	97:   {"Framed-IPv6-Prefix", "OctetString"},
	98:   {"Login-IPv6-Host", "OctetString"},
	99:   {"Framed-IPv6-Route", "UTF8String"},
	100:  {"Framed-IPv6-Pool", "OctetString"},
	101:  {"Error-Cause", "Integer32"},
	102:  {"EAP-Key-Name", "UTF8String"},
	103:  {"Digest-Response", "UTF8String"},
	104:  {"Digest-Realm", "UTF8String"},
	105:  {"Digest-Nonce", "UTF8String"},
	106:  {"Digest-Response-Auth", "UTF8String"},
	107:  {"Digest-Nextnonce", "UTF8String"},
	108:  {"Digest-Method", "UTF8String"},
	109:  {"Digest-URI", "UTF8String"},
	110:  {"Digest-Qop", "UTF8String"},
	111:  {"Digest-Algorithm", "UTF8String"},
	112:  {"Digest-Entity-Body-Hash", "UTF8String"},
	113:  {"Digest-Digest-CNonce", "UTF8String"},
	114:  {"Digest-Nonce-Count", "UTF8String"},
	115:  {"Digest-Username", "UTF8String"},
	116:  {"Digest-Opaque", "UTF8String"},
	117:  {"Digest-Auth-Param", "UTF8String"},
	118:  {"Digest-AKA-Auts", "UTF8String"},
	119:  {"Digest-Domain", "UTF8String"},
	120:  {"Digest-Stale", "UTF8String"},
	121:  {"Digest-HA1", "UTF8String"},
	122:  {"SIP-AOR", "UTF8String"},
	123:  {"Delegated-IPv6-Prefix", "OctetString"},
	124:  {"MIP6-Feature-Vector", "Unsigned64"},
	125:  {"MIP6-Home-Link-Prefix", "OctetString"},
	126:  {"Operator-Name", "OctetString"},
	127:  {"Location-Information", "OctetString"},
	128:  {"Location-Data", "OctetString"},
	129:  {"Basic-Location-Policy-Rules", "OctetString"},
	130:  {"Extended-Location-Policy-Rules", "OctetString"},
	131:  {"Location-Capable", "OctetString"},
	132:  {"Requested-Location-Info", "OctetString"},
	133:  {"Framed-Management-Protocol", "Enumerated"},
	134:  {"Management-Transport-Protection", "Enumerated"},
	135:  {"Management-Policy-Id", "UTF8String"},
	136:  {"Management-Privilege-Level", "Integer32"},
	137:  {"PKM-SS-Cert", "OctetString"},
	138:  {"PKM-CA-Cert", "OctetString"},
	139:  {"PKM-Config-Settings", "OctetString"},
	140:  {"PKM-Cryptosuite-List", "OctetString"},
	141:  {"PPKM-SAID", "OctetString"},
	142:  {"PKM-SA-Descriptor", "OctetString"},
	143:  {"PKM-Auth-Key", "OctetString"},
	144:  {"Unassigned", "OctetString"},
	145:  {"Unassigned", "OctetString"},
	146:  {"Unassigned", "OctetString"},
	147:  {"Unassigned", "OctetString"},
	148:  {"Unassigned", "OctetString"},
	149:  {"Unassigned", "OctetString"},
	150:  {"Unassigned", "OctetString"},
	151:  {"Unassigned", "OctetString"},
	152:  {"Unassigned", "OctetString"},
	153:  {"Unassigned", "OctetString"},
	154:  {"Unassigned", "OctetString"},
	155:  {"Unassigned", "OctetString"},
	156:  {"Unassigned", "OctetString"},
	157:  {"Unassigned", "OctetString"},
	158:  {"Unassigned", "OctetString"},
	159:  {"Unassigned", "OctetString"},
	160:  {"Unassigned", "OctetString"},
	161:  {"Unassigned", "OctetString"},
	162:  {"Unassigned", "OctetString"},
	163:  {"Unassigned", "OctetString"},
	164:  {"Unassigned", "OctetString"},
	165:  {"Unassigned", "OctetString"},
	166:  {"Unassigned", "OctetString"},
	167:  {"Unassigned", "OctetString"},
	168:  {"Unassigned", "OctetString"},
	169:  {"Unassigned", "OctetString"},
	170:  {"Unassigned", "OctetString"},
	171:  {"Unassigned", "OctetString"},
	172:  {"Unassigned", "OctetString"},
	173:  {"Unassigned", "OctetString"},
	174:  {"Unassigned", "OctetString"},
	175:  {"Unassigned", "OctetString"},
	176:  {"Unassigned", "OctetString"},
	177:  {"Unassigned", "OctetString"},
	178:  {"Unassigned", "OctetString"},
	179:  {"Unassigned", "OctetString"},
	180:  {"Unassigned", "OctetString"},
	181:  {"Unassigned", "OctetString"},
	182:  {"Unassigned", "OctetString"},
	183:  {"Unassigned", "OctetString"},
	184:  {"Unassigned", "OctetString"},
	185:  {"Unassigned", "OctetString"},
	186:  {"Unassigned", "OctetString"},
	187:  {"Unassigned", "OctetString"},
	188:  {"Unassigned", "OctetString"},
	189:  {"Unassigned", "OctetString"},
	190:  {"Unassigned", "OctetString"},
	191:  {"Unassigned", "OctetString"},
	192:  {"Experimental-Use", "OctetString"},
	193:  {"Experimental-Use", "OctetString"},
	194:  {"Experimental-Use", "OctetString"},
	195:  {"Experimental-Use", "OctetString"},
	196:  {"Experimental-Use", "OctetString"},
	197:  {"Experimental-Use", "OctetString"},
	198:  {"Experimental-Use", "OctetString"},
	199:  {"Experimental-Use", "OctetString"},
	200:  {"Experimental-Use", "OctetString"},
	201:  {"Experimental-Use", "OctetString"},
	202:  {"Experimental-Use", "OctetString"},
	203:  {"Experimental-Use", "OctetString"},
	204:  {"Experimental-Use", "OctetString"},
	205:  {"Experimental-Use", "OctetString"},
	206:  {"Experimental-Use", "OctetString"},
	207:  {"Experimental-Use", "OctetString"},
	208:  {"Experimental-Use", "OctetString"},
	209:  {"Experimental-Use", "OctetString"},
	210:  {"Experimental-Use", "OctetString"},
	211:  {"Experimental-Use", "OctetString"},
	212:  {"Experimental-Use", "OctetString"},
	213:  {"Experimental-Use", "OctetString"},
	214:  {"Experimental-Use", "OctetString"},
	215:  {"Experimental-Use", "OctetString"},
	216:  {"Experimental-Use", "OctetString"},
	217:  {"Experimental-Use", "OctetString"},
	218:  {"Experimental-Use", "OctetString"},
	219:  {"Experimental-Use", "OctetString"},
	220:  {"Experimental-Use", "OctetString"},
	221:  {"Experimental-Use", "OctetString"},
	222:  {"Experimental-Use", "OctetString"},
	223:  {"Experimental-Use", "OctetString"},
	224:  {"Implementation-Specific", "OctetString"},
	225:  {"Implementation-Specific", "OctetString"},
	226:  {"Implementation-Specific", "OctetString"},
	227:  {"Implementation-Specific", "OctetString"},
	228:  {"Implementation-Specific", "OctetString"},
	229:  {"Implementation-Specific", "OctetString"},
	230:  {"Implementation-Specific", "OctetString"},
	231:  {"Implementation-Specific", "OctetString"},
	232:  {"Implementation-Specific", "OctetString"},
	233:  {"Implementation-Specific", "OctetString"},
	234:  {"Implementation-Specific", "OctetString"},
	235:  {"Implementation-Specific", "OctetString"},
	236:  {"Implementation-Specific", "OctetString"},
	237:  {"Implementation-Specific", "OctetString"},
	238:  {"Implementation-Specific", "OctetString"},
	239:  {"Implementation-Specific", "OctetString"},
	240:  {"Implementation-Specific", "OctetString"},
	241:  {"Reserved", "OctetString"},
	242:  {"Reserved", "OctetString"},
	243:  {"Reserved", "OctetString"},
	244:  {"Reserved", "OctetString"},
	245:  {"Reserved", "OctetString"},
	246:  {"Reserved", "OctetString"},
	247:  {"Reserved", "OctetString"},
	248:  {"Reserved", "OctetString"},
	249:  {"Reserved", "OctetString"},
	250:  {"Reserved", "OctetString"},
	251:  {"Reserved", "OctetString"},
	252:  {"Reserved", "OctetString"},
	253:  {"Reserved", "OctetString"},
	254:  {"Reserved", "OctetString"},
	255:  {"Reserved", "OctetString"},
	256:  {"Unassigned", "OctetString"},
	257:  {"Host-IP-Address", "IPAddress"},
	258:  {"Auth-Application-Id", "AppId"},
	259:  {"Acct-Application-Id", "AppId"},
	260:  {"Vendor-Specific-Application-Id", "Grouped"},
	261:  {"Redirect-Host-Usage", "Enumerated"},
	262:  {"Redirect-Max-Cache-Time", "Unsigned32"},
	263:  {"Session-Id", "UTF8String"},
	264:  {"Origin-Host", "DiameterIdentity"},
	265:  {"Supported-Vendor-Id", "VendorId"},
	266:  {"Vendor-Id", "VendorId"},
	267:  {"Firmware-Revision", "Unsigned32"},
	268:  {"Result-Code", "Unsigned32"},
	269:  {"Product-Name", "UTF8String"},
	270:  {"Session-Binding", "Unsigned32"},
	271:  {"Session-Server-Failover", "Unsigned32"},
	272:  {"Multi-Round-Time-Out", "Unsigned32"},
	273:  {"Disconnect-Cause", "Enumerated"},
	274:  {"Auth-Request-Type", "Unsigned32"},
	275:  {"Alternate-Peer", "DiameterIdentity"},
	276:  {"Auth-Grace-Period", "Unsigned32"},
	277:  {"Auth-Session-State", "Unsigned32"},
	278:  {"Origin-State-Id", "Unsigned32"},
	279:  {"Failed-AVP", "Grouped"},
	280:  {"Proxy-Host", "DiameterIdentity"},
	281:  {"Error-Message", "UTF8String"},
	282:  {"Route-Record", "DiameterIdentity"},
	283:  {"Destination-Realm", "DiameterIdentity"},
	284:  {"Proxy-Info", "Grouped"},
	285:  {"Re-Auth-Request-Type", "Unsigned32"},
	286:  {"Unassigned", "OctetString"},
	287:  {"Accounting-Sub-Session-Id", "Unsigned64"},
	288:  {"Unallocated", "OctetString"},
	289:  {"Unallocated", "OctetString"},
	290:  {"Unallocated", "OctetString"},
	291:  {"Authorization-Lifetime", "Integer32"},
	292:  {"Redirect-Host", "DiameterURI"},
	293:  {"Destination-Host", "DiameterIdentity"},
	294:  {"Error-Reporting-Host", "DiameterIdentity"},
	295:  {"Termination-Cause", "Enumerated"},
	296:  {"Origin-Realm", "DiameterIdentity"},
	297:  {"Experimental-Result", "Grouped"},
	298:  {"Experimental-Result-Code", "Unsigned32"},
	299:  {"Inband-Security-Id", "Unsigned32"},
	300:  {"E2E-Sequence", "Grouped"},
	301:  {"Unallocated", "OctetString"},
	302:  {"Unallocated", "OctetString"},
	303:  {"Unallocated", "OctetString"},
	304:  {"Unallocated", "OctetString"},
	305:  {"Unallocated", "OctetString"},
	306:  {"Unallocated", "OctetString"},
	307:  {"Unallocated", "OctetString"},
	308:  {"Unallocated", "OctetString"},
	309:  {"Unallocated", "OctetString"},
	310:  {"Unallocated", "OctetString"},
	311:  {"Unallocated", "OctetString"},
	312:  {"Unallocated", "OctetString"},
	313:  {"Unallocated", "OctetString"},
	314:  {"Unallocated", "OctetString"},
	315:  {"Unallocated", "OctetString"},
	316:  {"Unallocated", "OctetString"},
	317:  {"Unallocated", "OctetString"},
	318:  {"MIP-FA-to-HA-SPI", "Unsigned32"},
	319:  {"MIP-FA-to-MN-SPI", "Unsigned32"},
	320:  {"MIP-Reg-Request", "OctetString"},
	321:  {"MIP-Reg-Reply", "OctetString"},
	322:  {"MIP-MN-AAA-Auth", "Grouped"},
	323:  {"MIP-HA-to-FA-SPI", "Unsigned32"},
	324:  {"Unassigned", "OctetString"},
	325:  {"MIP-MN-to-FA-MSA", "Grouped"},
	326:  {"MIP-FA-to-MN-MSA", "Grouped"},
	327:  {"Unassigned", "OctetString"},
	328:  {"MIP-FA-to-HA-MSA", "Grouped"},
	329:  {"MIP-HA-to-FA-MSA", "Grouped"},
	330:  {"Unassigned", "OctetString"},
	331:  {"MIP-MN-to-HA-MSA", "Grouped"},
	332:  {"MIP-HA-to-MN-MSA", "Grouped"},
	333:  {"MIP-Mobile-Node-Address", "IPAddress"},
	334:  {"MIP-Home-Agent-Address", "IPAddress"},
	335:  {"MIP-Nonce", "OctetString"},
	336:  {"MIP-Candidate-Home-Agent-Host", "DiameterIdentity"},
	337:  {"MIP-Feature-Vector", "Unsigned32"},
	338:  {"MIP-Auth-Input-Data-Length", "Unsigned32"},
	339:  {"MIP-Authenticator-Length", "Unsigned32"},
	340:  {"MIP-Authenticator-Offset", "Unsigned32"},
	341:  {"MIP-MN-AAA-SPI", "Unsigned32"},
	342:  {"MIP-Filter-Rule", "IPFilterRule"},
	343:  {"MIP-Session-Key", "OctetString"},
	344:  {"MIP-FA-Challenge", "OctetString"},
	345:  {"MIP-Algorithm-Type", "Unsigned32"},
	346:  {"MIP-Replay-Mode", "Unsigned32"},
	347:  {"MIP-Originating-Foreign-AAA", "Grouped"},
	348:  {"MIP-Home-Agent-Host", "Grouped"},
	349:  {"Unassigned", "OctetString"},
	350:  {"Unassigned", "OctetString"},
	351:  {"Unassigned", "OctetString"},
	352:  {"Unassigned", "OctetString"},
	353:  {"Unassigned", "OctetString"},
	354:  {"Unassigned", "OctetString"},
	355:  {"Unassigned", "OctetString"},
	356:  {"Unassigned", "OctetString"},
	357:  {"Unassigned", "OctetString"},
	358:  {"Unassigned", "OctetString"},
	359:  {"Unassigned", "OctetString"},
	360:  {"Unassigned", "OctetString"},
	361:  {"Unassigned", "OctetString"},
	362:  {"Unassigned", "OctetString"},
	363:  {"Accounting-Input-Octets", "Unsigned64"},
	364:  {"Accounting-Output-Octets", "Unsigned64"},
	365:  {"Accounting-Input-Packets", "Unsigned64"},
	366:  {"Accounting-Output-Packets", "Unsigned64"},
	367:  {"MIP-MSA-Lifetime", "Unsigned32"},
	368:  {"SIP-Accounting-Information", "Grouped"},
	369:  {"SIP-Accounting-Server-URI", "DiameterURI"},
	370:  {"SIP-Credit-Control-Server-URI", "DiameterURI"},
	371:  {"SIP-Server-URI", "UTF8String"},
	372:  {"SIP-Server-Capabilities", "Grouped"},
	373:  {"SIP-Mandatory-Capability", "Unsigned32"},
	374:  {"SIP-Optional-Capability", "Unsigned32"},
	375:  {"SIP-Server-Assignment-Type", "Enumerated"},
	376:  {"SIP-Auth-Data-Item", "Grouped"},
	377:  {"SIP-Authentication-Scheme", "Enumerated"},
	378:  {"SIP-Item-Number", "Unsigned32"},
	379:  {"SIP-Authenticate", "Grouped"},
	380:  {"SIP-Authorization", "Grouped"},
	381:  {"SIP-Authentication-Info", "Grouped"},
	382:  {"SIP-Number-Auth-Items", "Unsigned32"},
	383:  {"SIP-Deregistration-Reason", "Grouped"},
	384:  {"SIP-Reason-Code", "Enumerated"},
	385:  {"SIP-Reason-Info", "UTF8String"},
	386:  {"SIP-Visited-Network-Id", "UTF8String"},
	387:  {"SIP-User-Authorization-Type", "Enumerated"},
	388:  {"SIP-Supported-User-Data-Type", "UTF8String"},
	389:  {"SIP-User-Data", "Grouped"},
	390:  {"SIP-User-Data-Type", "UTF8String"},
	391:  {"SIP-User-Data-Contents", "OctetString"},
	392:  {"SIP-User-Data-Already-Available", "Enumerated"},
	393:  {"SIP-Method", "UTF8String"},
	394:  {"Unassigned", "OctetString"},
	395:  {"Unassigned", "OctetString"},
	396:  {"Unassigned", "OctetString"},
	397:  {"Unassigned", "OctetString"},
	398:  {"Unassigned", "OctetString"},
	399:  {"Unassigned", "OctetString"},
	400:  {"NAS-Filter-Rule", "IPFilterRule"},
	401:  {"Tunneling", "Grouped"},
	402:  {"CHAP-Auth", "Grouped"},
	403:  {"CHAP-Algorithm", "Enumerated"},
	404:  {"CHAP-Ident", "OctetString"},
	405:  {"CHAP-Response", "OctetString"},
	406:  {"Accounting-Auth-Method", "Enumerated"},
	407:  {"QoS-Filter-Rule", "QoSFilterRule"},
	408:  {"Origin-AAA-Protocol", "Enumerated"},
	409:  {"Unassigned", "OctetString"},
	410:  {"Unassigned", "OctetString"},
	411:  {"CC-Correlation-Id", "OctetString"},
	412:  {"CC-Input-Octets", "Unsigned64"},
	413:  {"CC-Money", "Grouped"},
	414:  {"CC-Output-Octets", "Unsigned64"},
	415:  {"CC-Request-Number", "Unsigned32"},
	416:  {"CC-Request-Type", "Unsigned32"},
	417:  {"CC-Service-Specific-Units", "Unsigned64"},
	418:  {"CC-Session-Failover", "Enumerated"},
	419:  {"CC-Sub-Session-Id", "Unsigned64"},
	420:  {"CC-Time", "Unsigned32"},
	421:  {"CC-Total-Octets", "Unsigned64"},
	422:  {"Check-Balance-Result", "Enumerated"},
	423:  {"Cost-Information", "Grouped"},
	424:  {"Cost-Unit", "UTF8String"},
	425:  {"Currency-Code", "Unsigned32"},
	426:  {"Credit-Control", "Enumerated"},
	427:  {"Credit-Control-Failure-Handling", "Enumerated"},
	428:  {"Direct-Debiting-Failure-Handling", "Enumerated"},
	429:  {"Exponent", "Integer32"},
	430:  {"Final-Unit-Indication", "Grouped"},
	431:  {"Granted-Service-Unit", "Grouped"},
	432:  {"Rating-Group", "Unsigned32"},
	433:  {"Redirect-Address-Type", "Enumerated"},
	434:  {"Redirect-Server", "Grouped"},
	435:  {"Redirect-Server-Address", "UTF8String"},
	436:  {"Requested-Action", "Unsigned32"},
	437:  {"Requested-Service-Unit", "Grouped"},
	438:  {"Restricted-Filter-Rule", "IPFilterRule"},
	439:  {"Service-Identifier", "Unsigned32"},
	440:  {"Service-Parameter-Info", "Grouped"},
	441:  {"Service-Parameter-Type", "Unsigned32"},
	442:  {"Service-Parameter-Value", "OctetString"},
	443:  {"Subscription-Id", "Grouped"},
	444:  {"Subscription-Id-Data", "UTF8String"},
	445:  {"Unit-Value", "Grouped"},
	446:  {"Used-Service-Unit", "Grouped"},
	447:  {"Value-Digits", "Integer64"},
	448:  {"Validity-Time", "Unsigned32"},
	449:  {"Final-Unit-Action", "Enumerated"},
	450:  {"Subscription-Id-Type", "Unsigned32"},
	451:  {"Tariff-Time-Change", "Time"},
	452:  {"Tariff-Change-Usage", "Enumerated"},
	453:  {"G-S-U-Pool-Identifier", "Unsigned32"},
	454:  {"CC-Unit-Type", "Enumerated"},
	455:  {"Multiple-Services-Indicator", "Enumerated"},
	456:  {"Multiple-Services-Credit-Control", "Grouped"},
	457:  {"G-S-U-Pool-Reference", "Grouped"},
	458:  {"User-Equipment-Info", "Grouped"},
	459:  {"User-Equipment-Info-Type", "Enumerated"},
	460:  {"User-Equipment-Info-Value", "OctetString"},
	461:  {"Service-Context-Id", "UTF8String"},
	462:  {"EAP-Payload", "OctetString"},
	463:  {"EAP-Reissued-Payload", "OctetString"},
	464:  {"EAP-Master-Session-Key", "OctetString"},
	465:  {"Accounting-EAP-Auth-Method", "Unsigned64"},
	466:  {"Unassigned", "OctetString"},
	467:  {"Unassigned", "OctetString"},
	468:  {"Unassigned", "OctetString"},
	469:  {"Unassigned", "OctetString"},
	470:  {"Unassigned", "OctetString"},
	471:  {"Unassigned", "OctetString"},
	472:  {"Unassigned", "OctetString"},
	473:  {"Unassigned", "OctetString"},
	474:  {"Unassigned", "OctetString"},
	475:  {"Unassigned", "OctetString"},
	476:  {"Unassigned", "OctetString"},
	477:  {"Unassigned", "OctetString"},
	478:  {"Unassigned", "OctetString"},
	479:  {"Unassigned", "OctetString"},
	480:  {"Accounting-Record-Type", "Enumerated"},
	481:  {"Unassigned", "OctetString"},
	482:  {"Unassigned", "OctetString"},
	483:  {"Accounting-Realtime-Required", "Unsigned32"},
	484:  {"Unassigned", "OctetString"},
	485:  {"Accounting-Record-Number", "Unsigned32"},
	486:  {"MIP6-Agent-Info", "Grouped"},
	493:  {"Service-Selection", "UTF8String"},
	495:  {"TMOD-1", "Grouped"},
	496:  {"Token-Rate", "Float32"},
	497:  {"Bucket-Depth", "Float32"},
	498:  {"Peak-Traffic-Rate", "Float32"},
	499:  {"Minimum-Policed-Unit", "Unsigned32"},
	500:  {"Maximum-Packet-Size", "Unsigned32"},
	501:  {"TMOD-2", "Grouped"},
	502:  {"Bandwidth", "Float32"},
	503:  {"PHB-Class", "Unsigned32"},
	506:  {"Mobile-Node-Identifier", "UTF8String"},
	508:  {"Flow-Grouping", "Grouped"},
	510:  {"Flows", "Grouped"},
	517:  {"Media-Component-Description", "Grouped"},
	519:  {"Media-Sub-Component", "Grouped"},
	1472: {"Specific-APN-Info", "Grouped"},
	6063: {"QoS-Capability", "Grouped"},
	6064: {"Vendor-Specific-QoS-Profile-Template", "Grouped"},
	6065: {"QoS-Resources", "Grouped"},
	6066: {"Extended-QoS-Filter-Rule", "Grouped"},
	6067: {"QoS-Profile-Template", "Unsigned32"},
	9938: {"Timezone-Flag", "Enumerated"},
	9939: {"Absolute-Stop-Time", "Time"},
	9940: {"Absolute-Start-Time", "Time"},
	9941: {"Month-Of-Year-Mask", "Unsigned32"},
	9942: {"Day-Of-Month-Mask", "Unsigned32"},
	9943: {"Day-Of-Week-Mask", "Unsigned32"},
	9944: {"Time-Of-Day-End", "Unsigned32"},
	9945: {"Time-Of-Day-Start", "Unsigned32"},
	9946: {"Time-Of-Day-Condition", "Grouped"},
	9947: {"ETH-High-Priority", "Unsigned32"},
	9948: {"ETH-Low-Priority", "Unsigned32"},
	9949: {"ETH-Priority-Range", "Grouped"},
	9950: {"C-VID-End", "Unsigned32"},
	9951: {"C-VID-Start", "Unsigned32"},
	9952: {"S-VID-End", "Unsigned32"},
	9953: {"S-VID-Start", "Unsigned32"},
	9954: {"VLAN-ID-Range", "Grouped"},
	9955: {"ETH-SAP", "OctetString"},
	9956: {"ETH-Ether-Type", "OctetString"},
	9957: {"ETH-Proto-Type", "Grouped"},
	9958: {"ETH-Option", "Grouped"},
	9959: {"ICMP-Type-Number", "Enumerated"},
	9960: {"ICMP-Type", "Grouped"},
	9961: {"TCP-Flag-Type", "Enumerated"},
	9962: {"TCP-Flags", "Grouped"},
	9963: {"TCP-Option-Type", "Enumerated"},
	9964: {"TCP-Option", "Grouped"},
	9965: {"IP-Option-Value", "OctetString"},
	9966: {"IP-Option-Type", "Enumerated"},
	9967: {"IP-Option", "Grouped"},
	9968: {"Fragementation-Flag", "Enumerated"},
	9969: {"Diffserv-Code-Point", "Enumerated"},
	9970: {"Use-Assigned-Address", "Enumerated"},
	9971: {"Negated", "Enumerated"},
	9972: {"Port-End", "Integer32"},
	9973: {"Port-Start", "Integer32"},
	9974: {"Port-Range", "Grouped"},
	9975: {"Port", "Integer32"},
	9976: {"EUI64-Address-Mask-Pattern", "OctetString"},
	9978: {"EUI64-Address-Mask", "Grouped"},
	9979: {"EUI64-Address", "OctetString"},
	9980: {"MAC-Address-Mask-Pattern", "OctetString"},
	9981: {"MAC-Address-Mask", "Grouped"},
	9982: {"MAC-Address", "OctetString"},
	9983: {"IP-Bit-Mask-Width", "OctetString"},
	9984: {"IP-Address-Mask", "Grouped"},
	9985: {"IP-Address-End", "Address"},
	9986: {"IP-Address-Start", "Address"},
	9987: {"IP-Address-Range", "Grouped"},
	9988: {"IP-Address", "Address"},
	9989: {"To-Spec", "Grouped"},
	9990: {"From-Spec", "Grouped"},
	9991: {"QSPEC-Type", "Unsigned32"},
	9992: {"QoS-Semantics", "Enumerated"},
	9993: {"QoS-Parameters", "OctetString"},
	9994: {"QoS-Rule-Precedence", "Unsigned32"},
	9995: {"Classifier", "Grouped"},
	9997: {"Classifier-ID AVP", "OctetString"},
	9998: {"Protocol", "Enumerated"},
	9999: {"Direction", "Enumerated"},
}

var vendorsAvps = map[uint32]map[uint32]avpType{
	10415: {
		507:  avpType{"3GPP-Flow-Description", "IPFilterRule"},
		603:  avpType{"Server-Capabilities", "Grouped"},
		1055: avpType{"QoS-Rule-Report", "Grouped"},
		1056: avpType{"Security-Parameter-Index", "OctetString"},
		1057: avpType{"Flow-Label", "OctetString"},
		1058: avpType{"Flow-Information", "Grouped"},
		1059: avpType{"Packet-Filter-Content", "IPFilterRule"},
		1060: avpType{"Packet-Filter-Identifier", "OctetString"},
		300:  avpType{"Authentication-Method", "Enumerated"},
		301:  avpType{"Authentication-Information-SIM", "OctetString"},
		302:  avpType{"Authorization-Information-SIM", "OctetString"},
		303:  avpType{"WLAN-User-Data", "Grouped"},
		304:  avpType{"Charging-Data", "Grouped"},
		305:  avpType{"WLAN-Access", "Enumerated"},
		306:  avpType{"WLAN-3GPP-IP-Access", "Enumerated"},
		307:  avpType{"APN-Authorized", "Grouped"},
		309:  avpType{"APN-Barring-Type", "Enumerated"},
		310:  avpType{"WLAN-Direct-IP-Access", "Enumerated"},
		311:  avpType{"Session-Request-Type", "Enumerated"},
		312:  avpType{"Routing-Policy", "IPFilterRule"},
		313:  avpType{"Max-Requested-Bandwidth", "OctetString"},
		314:  avpType{"Charging-Characteristics", "Integer"},
		315:  avpType{"Charging-Nodes", "Grouped"},
		316:  avpType{"Primary-OCS-Charging-Function-Name", "DiameterIdentity"},
		317:  avpType{"Secondary-OCS-Charging-Function-Name", "DiameterIdentity"},
		318:  avpType{"3GPP-AAA-Server-Name", "DiameterIdentity"},
		319:  avpType{"Maximum-Number-Accesses", "Unsigned32"},
		378:  avpType{"3GPP-SIP-Item-Number", "Unsigned32"},
		400:  avpType{"GBA-UserSecSettings", "OctetString"},
		401:  avpType{"Transaction-Identifier", "OctetString"},
		402:  avpType{"NAF-Hostname", "OctetString"},
		403:  avpType{"GAA-Service-Identifier", "OctetString"},
		404:  avpType{"Key-ExpiryTime", "Time"},
		405:  avpType{"ME-Key-Material", "OctetString"},
		406:  avpType{"UICC-Key-Material", "OctetString"},
		407:  avpType{"GBA_U-Awareness-Indicator", "Enumerated"},
		408:  avpType{"BootstrapInfoCreationTime", "Time"},
		409:  avpType{"GUSS-Timestamp", "Time"},
		410:  avpType{"GBA-Type", "Enumerated"},
		411:  avpType{"UE-Id", "OctetString"},
		412:  avpType{"UE-Id-Type", "Enumerated"},
		413:  avpType{"UICC-App-Label", "OctetString"},
		414:  avpType{"UICC-ME", "Enumerated"},
		415:  avpType{"Requested-Key-Lifetime", "Time"},
		416:  avpType{"Private-Identity-Request", "Enumerated"},
		417:  avpType{"GBA-Push-Info", "OctetString"},
		418:  avpType{"NAF-SA-Identifier", "OctetString"},
		419:  avpType{"Security-Feature-Request", "OctetString"},
		420:  avpType{"Security-Feature-Response", "OctetString"},
		500:  avpType{"Abort-Cause", "Enumerated"},
		501:  avpType{"Access-Network-Charging-Address", "IPAddress"},
		502:  avpType{"Access-Network-Charging-Identifier", "Grouped"},
		503:  avpType{"Access-Network-Charging-Identifier-Value", "OctetString"},
		504:  avpType{"AF-Application-Identifier", "OctetString"},
		505:  avpType{"AF-Charging-Identifier", "OctetString"},
		506:  avpType{"Authorization-Token", "OctetString"},
		508:  avpType{"3GPP-Flow-Grouping", "Grouped"},
		509:  avpType{"Flow-Number", "Unsigned32"},
		510:  avpType{"3GPP-Flows", "Grouped"},
		511:  avpType{"Flow-Status", "Enumerated"},
		512:  avpType{"Flow-Usage", "Enumerated"},
		513:  avpType{"Specific-Action", "Enumerated"},
		515:  avpType{"Max-Requested-Bandwidth-DL", "Unsigned32"},
		516:  avpType{"Max-Requested-Bandwidth-UL", "Unsigned32"},
		517:  avpType{"3GPP-Media-Component-Description", "Grouped"},
		518:  avpType{"Media-Component-Number", "Unsigned32"},
		519:  avpType{"3GPP-Media-Sub-Component", "Grouped"},
		520:  avpType{"Media-Type", "Enumerated"},
		521:  avpType{"RR-Bandwidth", "Unsigned32"},
		1:    avpType{"3GPP-IMSI", "UTF8String"},
		2:    avpType{"3GPP-Charging-Id", "Integer32"},
		3:    avpType{"3GPP-PDP-Type", "Integer32"},
		4:    avpType{"3GPP-CG-Address", "IPAddress"},
		5:    avpType{"3GPP-GPRS-Negotiated-QoS-profile", "UTF8String"},
		6:    avpType{"3GPP-SGSN-Address", "IPAddress"},
		7:    avpType{"3GPP-GGSN-Address", "IPAddress"},
		8:    avpType{"3GPP-IMSI-MCC-MNC", "UTF8String"},
		9:    avpType{"3GPP-GGSN-MCC-MNC", "UTF8String"},
		10:   avpType{"3GPP-NSAPI", "UTF8String"},
		11:   avpType{"3GPP-Session-Stop-Indicator", "UTF8String"},
		12:   avpType{"3GPP-Selection-Mode", "UTF8String"},
		13:   avpType{"3GPP-Charging-Characteristics", "UTF8String"},
		14:   avpType{"3GPP-CG-IPv6-Address", "OctetString"},
		15:   avpType{"3GPP-SGSN-IPv6-Address", "OctetString"},
		16:   avpType{"3GPP-GGSN-IPv6-Address", "OctetString"},
		17:   avpType{"3GPP-IPv6-DNS-Server", "OctetString"},
		18:   avpType{"3GPP-SGSN-MCC-MNC", "UTF8String"},
		19:   avpType{"3GPP-Teardown-Indicator", "OctetString"},
		20:   avpType{"3GPP-IMEISV", "OctetString"},
		21:   avpType{"3GPP-RAT-Type", "OctetString"},
		22:   avpType{"3GPP-User-Location-Info", "OctetString"},
		23:   avpType{"3GPP-MS-TimeZone", "OctetString"},
		24:   avpType{"3GPP-CAMEL-Charging-Info", "OctetString"},
		25:   avpType{"3GPP-Packet-Filter", "OctetString"},
		26:   avpType{"3GPP-Negotiated-DSCP", "OctetString"},
		27:   avpType{"3GPP-Allocate-IP-Type", "OctetString"},
		522:  avpType{"RS-Bandwidth", "Unsigned32"},
		523:  avpType{"SIP-Forking-Indication", "Enumerated"},
		524:  avpType{"Codec-Data AVP", "UTF8String"},
		525:  avpType{"Service-URN", "OctetString"},
		526:  avpType{"Acceptable-Service-Info", "Grouped"},
		527:  avpType{"Service-Info-Status", "Enumerated"},
		600:  avpType{"Visited-Network-Identifier", "OctetString"},
		601:  avpType{"Public-Identity", "UTF8String"},
		602:  avpType{"Server-Name", "UTF8String"},
		604:  avpType{"Mandatory-Capability", "Unsigned32"},
		605:  avpType{"Optional-Capability", "Unsigned32"},
		606:  avpType{"User-Data", "OctetString"},
		607:  avpType{"3GPP-SIP-Number-Auth-Items", "Unsigned32"},
		608:  avpType{"3GPP-SIP-Authentication-Scheme", "UTF8String"},
		609:  avpType{"3GPP-SIP-Authenticate", "OctetString"},
		610:  avpType{"3GPP-SIP-Authorization", "OctetString"},
		611:  avpType{"3GPP-SIP-Authentication-Context", "OctetString"},
		612:  avpType{"3GPP-SIP-Auth-Data-Item", "Grouped"},
		613:  avpType{"TGPP-SIP-Item-Number", "Unsigned32"},
		614:  avpType{"Server-Assignment-Type", "Enumerated"},
		615:  avpType{"Deregistration-Reason", "Grouped"},
		616:  avpType{"Reason-Code", "Enumerated"},
		617:  avpType{"Reason-Info", "UTF8String"},
		618:  avpType{"Charging-Information", "Grouped"},
		619:  avpType{"Primary-Event-Charging-Function-Name", "DiameterURI"},
		620:  avpType{"Secondary-Event-Charging-Function-Name", "DiameterURI"},
		621:  avpType{"Primary-Charging-Collection-Function-Name", "DiameterURI"},
		622:  avpType{"Secondary-Charging-Collection-Function-Name", "DiameterURI"},
		623:  avpType{"User-Authorization-Type", "Enumerated"},
		624:  avpType{"User-Data-Already-Available", "Enumerated"},
		625:  avpType{"Confidentiality-Key", "OctetString"},
		626:  avpType{"Integrity-Key", "OctetString"},
		627:  avpType{"User-Data-Request-Type(Obsolete)", "Unsigned32"},
		628:  avpType{"Supported-Features", "Grouped"},
		629:  avpType{"Feature-List-ID", "Unsigned32"},
		630:  avpType{"Feature-List", "Unsigned32"},
		631:  avpType{"Supported-Applications", "Grouped"},
		632:  avpType{"Associated-Identities", "Grouped"},
		633:  avpType{"Originating-Request", "Enumerated"},
		634:  avpType{"Wildcarded-PSI", "UTF8String"},
		635:  avpType{"SIP-Digest-Authenticate AVP", "Grouped"},
		636:  avpType{"Wildcarded-IMPU", "UTF8String"},
		637:  avpType{"UAR-Flags", "Unsigned32"},
		638:  avpType{"Loose-Route-Indication", "Enumerated"},
		639:  avpType{"SCSCF-Restoration-Info", "Grouped"},
		640:  avpType{"Path", "OctetString"},
		641:  avpType{"Contact", "OctetString"},
		642:  avpType{"Subscription-Info", "Grouped"},
		643:  avpType{"Call-ID-SIP-Header", "OctetString"},
		644:  avpType{"From-SIP-Header", "OctetString"},
		645:  avpType{"To-SIP-Header", "OctetString"},
		646:  avpType{"Record-Route", "OctetString"},
		647:  avpType{"Associated-Registered-Identities", "Grouped"},
		648:  avpType{"Multiple-Registration-Indication", "Enumerated"},
		649:  avpType{"Restoration-Info", "Grouped"},
		650:  avpType{"Session-Priority", "Enumerated"},
		700:  avpType{"User-Identity", "Grouped"},
		701:  avpType{"3GPP-MSISDN", "OctetString"},
		702:  avpType{"3GPP-User-Data", "OctetString"},
		703:  avpType{"Data-Reference", "Unsigned32"},
		704:  avpType{"Service-Indication", "OctetString"},
		705:  avpType{"Subs-Req-Type", "Unsigned32"},
		706:  avpType{"Requested-Domain", "Unsigned32"},
		707:  avpType{"Current-Location", "Unsigned32"},
		708:  avpType{"Identity-Set", "Unsigned32"},
		709:  avpType{"Expiry-Time", "Time"},
		710:  avpType{"Send-Data-Indication", "Enumerated"},
		711:  avpType{"DSAI-Tag", "OctetString"},
		713:  avpType{"One-Time-Notification", "Enumerated"},
		714:  avpType{"Requested-Nodes", "Unsigned32"},
		823:  avpType{"3GPP-Event-Type", "Grouped"},
		824:  avpType{"3GPP-SIP-Method", "UTF8String"},
		825:  avpType{"Event", "UTF8String"},
		826:  avpType{"Content-Type", "UTF8String"},
		827:  avpType{"Content-Length", "Unsigned32"},
		828:  avpType{"Content-Disposition", "UTF8String"},
		829:  avpType{"Role-Of-Node", "Enumerated"},
		830:  avpType{"User-Session-Id", "UTF8String"},
		831:  avpType{"Calling-Party-Address", "UTF8String"},
		832:  avpType{"Called-Party-Address", "UTF8String"},
		833:  avpType{"Time-Stamps", "Grouped"},
		834:  avpType{"SIP-Request-Timestamp", "Time"},
		835:  avpType{"SIP-Response-Timestamp", "Time"},
		836:  avpType{"Application-Server", "UTF8String"},
		837:  avpType{"Application-provided-Called-Party-Address", "UTF8String"},
		838:  avpType{"Inter-Operator-Identifier", "Grouped"},
		839:  avpType{"Originating-IOI", "UTF8String"},
		840:  avpType{"Terminating-IOI", "UTF8String"},
		841:  avpType{"IMS-Charging-Identifier", "UTF8String"},
		842:  avpType{"SDP-Session-Description", "UTF8String"},
		843:  avpType{"SDP-Media-components", "Grouped"},
		844:  avpType{"SDP-Media-Name", "UTF8String"},
		845:  avpType{"SDP-Media-Description", "UTF8String"},
		846:  avpType{"GPRS-Charging-ID", "UTF8String"},
		847:  avpType{"GGSN-Address", "IPAddress"},
		848:  avpType{"Served-Party-IP-Address", "IPAddress"},
		849:  avpType{"Authorised-QoS", "UTF8String"},
		850:  avpType{"Application-Server-Information", "Grouped"},
		851:  avpType{"Trunk-Group-ID", "Grouped"},
		852:  avpType{"Incoming-Trunk-Group-ID", "UTF8String"},
		853:  avpType{"Outgoing-Trunk-Group-ID", "UTF8String"},
		854:  avpType{"Bearer-Service", "OctetString"},
		855:  avpType{"Service-ID", "UTF8String"},
		856:  avpType{"Associated-URI", "UTF8String"},
		857:  avpType{"Charged-Party", "UTF8String"},
		858:  avpType{"PoC-Controlling-Address", "UTF8String"},
		859:  avpType{"PoC-Group-Name", "UTF8String"},
		860:  avpType{"Cause", "Grouped"},
		861:  avpType{"Cause-Code", "Enumerated"},
		862:  avpType{"Node-Functionality", "Unsigned32"},
		863:  avpType{"Service-Specific-Data", "UTF8String"},
		864:  avpType{"Originator", "Enumerated"},
		865:  avpType{"PS-Furnish-Charging-Information", "Grouped"},
		866:  avpType{"PS-Free-Format-Data", "OctetString"},
		867:  avpType{"PS-Append-Free-Format-Data", "Enumerated"},
		868:  avpType{"Time-Quota-Threshold", "Unsigned32"},
		869:  avpType{"Volume-Quota-Threshold", "Unsigned32"},
		870:  avpType{"Trigger-Type", "Enumerated"},
		871:  avpType{"Quota-Holding-Time", "Unsigned32"},
		872:  avpType{"Reporting-Reason", "Enumerated"},
		873:  avpType{"Service-Information", "Grouped"},
		874:  avpType{"PS-Information", "Grouped"},
		875:  avpType{"WLAN-Information", "Grouped"},
		876:  avpType{"IMS-Information", "Grouped"},
		877:  avpType{"MMS-Information", "Grouped"},
		878:  avpType{"LCS-Information", "Grouped"},
		879:  avpType{"PoC-Information", "Grouped"},
		880:  avpType{"MBMS-Information", "Grouped"},
		881:  avpType{"Quota-Consumption-Time", "Unsigned32"},
		882:  avpType{"Media-Initiator-Flag", "Enumerated"},
		883:  avpType{"PoC-Server-Role", "Enumerated"},
		884:  avpType{"PoC-Session-Type", "Enumerated"},
		885:  avpType{"Number-Of-Participants", "Integer32"},
		886:  avpType{"Originator-Address", "Grouped"},
		887:  avpType{"Participants-Involved", "UTF8String"},
		888:  avpType{"Expires", "Unsigned32"},
		889:  avpType{"Message-Body", "Grouped"},
		890:  avpType{"WAG-Address", "IPAddress"},
		891:  avpType{"WAG-PLMN-Id", "OctetString"},
		892:  avpType{"WLAN-Radio-Container", "Grouped"},
		893:  avpType{"WLAN-Technology", "Unsigned32"},
		894:  avpType{"WLAN-UE-Local-IPAddress", "IPAddress"},
		895:  avpType{"PDG-Address", "IPAddress"},
		896:  avpType{"PDG-Charging-Id", "Unsigned32"},
		897:  avpType{"Address-Data", "UTF8String"},
		898:  avpType{"Address-Domain", "Grouped"},
		899:  avpType{"Address-Type", "Enumerated"},
		900:  avpType{"TMGI", "OctetString"},
		901:  avpType{"Required-MBMS-Bearer-Capabilities", "UTF8String"},
		902:  avpType{"MBMS-StartStop-Indicatio", "Enumerated"},
		903:  avpType{"MBMS-Service-Area", "OctetString"},
		904:  avpType{"MBMS-Session-Duration", "Unsigned32"},
		905:  avpType{"Alternative-APN", "UTF8String"},
		906:  avpType{"MBMS-Service-Type", "Enumerated"},
		907:  avpType{"MBMS-2G-3G-Indicator", "Enumerated"},
		908:  avpType{"MBMS-Session-Identity", "OctetString"},
		909:  avpType{"RAI", "UTF8String"},
		910:  avpType{"Additional-MBMS-Trace-Info", "OctetString"},
		911:  avpType{"MBMS-Time-To-Data-Transfe", "Unsigned32"},
		912:  avpType{"MBMS-Session-Identity-Repetition-Number", "Unsigned32"},
		913:  avpType{"MBMS-Required-QoS", "UTF8String"},
		914:  avpType{"MBMS-Counting-Information", "Enumerated"},
		915:  avpType{"MBMS-User-Data-Mode-Indication", "Enumerated"},
		916:  avpType{"MBMS-GGSN-Address", "UTF8String"},
		917:  avpType{"MBMS-GGSN-IPv6-Address", "UTF8String"},
		918:  avpType{"MBMS-BMSC-SSM-IP-Address", "UTF8String"},
		919:  avpType{"MBMS-BMSC-SSM-IPv6-Address", "UTF8String"},
		920:  avpType{"MBMS-Flow-Identifier", "OctetString"},
		921:  avpType{"CN-IP-Multicast-Distribution", "Enumerated"},
		922:  avpType{"3GPP-CN-IP-Multicast-Distribution", "Enumerated"},
		923:  avpType{"MBMS-Access-Indicator", "Enumerated"},
		1013: avpType{"TFT-Packet-Filter-Information", "Grouped"},
		1020: avpType{"Bearer-Identifier", "OctetString"},
		1021: avpType{"Bearer-Operation", "Enumerated"},
		1022: avpType{"Access-Network-Charging-Identifier-Gx", "Grouped"},
		1023: avpType{"Bearer-Control-Mode", "Enumerated"},
		1024: avpType{"Network-Request-Support", "Enumerated"},
		1025: avpType{"Guaranteed-Bitrate-DL", "Unsigned32"},
		1026: avpType{"Guaranteed-Bitrate-UL", "Unsigned32"},
		1027: avpType{"IP-CAN-Type", "Enumerated"},
		1028: avpType{"QoS-Class-Identifier", "Enumerated"},
		1029: avpType{"QoS-Negotiation", "Enumerated"},
		1030: avpType{"QoS-Upgrade", "Enumerated"},
		1031: avpType{"Rule-Failure-Code", "Enumerated"},
		1032: avpType{"RAT-Type", "Enumerated"},
		1033: avpType{"Event-Report-Indication", "Grouped"},
		1034: avpType{"Allocation-Retention-Priority", "Grouped"},
		1035: avpType{"CoA-IP-Address", "IPAddress"},
		1036: avpType{"Tunnel-Header-Filter", "IPFilterRule"},
		1037: avpType{"Tunnel-Header-Length", "Unsigned32"},
		1038: avpType{"Tunnel-Information", "Grouped"},
		1039: avpType{"CoA-Information", "Grouped"},
		1040: avpType{"APN-Aggregate-Max-Bitrate-DL", "Unsigned32"},
		1041: avpType{"APN-Aggregate-Max-Bitrate-UL", "Unsigned32"},
		1042: avpType{"Revalidation-Time", "Time"},
		1043: avpType{"Rule-Activation-Time", "Time"},
		1044: avpType{"Rule-DeActivation-Time", "Time"},
		1045: avpType{"Session-Release-Cause", "Enumerated"},
		1046: avpType{"Priority-Level", "Unsigned32"},
		1047: avpType{"Pre-emption-Capability", "Enumerated"},
		1048: avpType{"Pre-emption-Vulnerability", "Enumerated"},
		1049: avpType{"Default-EPS-Bearer-QoS", "Grouped"},
		1050: avpType{"AN-GW-Address", "IPAddress"},
		1051: avpType{"QoS-Rule-Install", "Grouped"},
		1052: avpType{"QoS-Rule-Remove", "Grouped"},
		1053: avpType{"QoS-Rule-Definition", "Grouped"},
		1054: avpType{"QoS-Rule-Name", "OctetString"},
		1061: avpType{"Packet-Filter-Information", "Grouped"},
		1062: avpType{"Packet-Filter-Operation", "Enumerated"},
		1063: avpType{"Resource-Allocation-Notification", "Enumerated"},
		1064: avpType{"Session-Linking-Indicator", "Enumerated"},
		1065: avpType{"PDN-Connection-ID", "OctetString"},
		1066: avpType{"Monitoring-Key", "OctetString"},
		1067: avpType{"Usage-Monitoring-Information", "Grouped"},
		1068: avpType{"Usage-Monitoring-Level", "Enumerated"},
		1069: avpType{"Usage-Monitoring-Report", "Enumerated"},
		1070: avpType{"Usage-Monitoring-Support", "Enumerated"},
		1071: avpType{"CSG-Information-Reporting", "Enumerated"},
		1072: avpType{"Packet-Filter-Usage", "Enumerated"},
		1073: avpType{"Flow-Direction", "Enumerated"},
		1074: avpType{"QoS-Rule-Base-Name", "UTF8String"},
		1100: avpType{"Served-User-Identity", "Grouped"},
		1101: avpType{"VASP-ID", "UTF8String"},
		1102: avpType{"VAS-ID", "UTF8String"},
		1103: avpType{"Trigger-Event", "Enumerated"},
		1104: avpType{"Sender-Address", "UTF8String"},
		1105: avpType{"Initial-Recipient-Address", "Grouped"},
		1106: avpType{"Result-Recipient-Address", "Grouped"},
		1107: avpType{"Sequence-Number", "Unsigned32"},
		1108: avpType{"Recipient-Address", "UTF8String"},
		1109: avpType{"Routeing-Address", "UTF8String"},
		1110: avpType{"Originating-Interface", "Enumerated"},
		1111: avpType{"Delivery-Report", "Enumerated"},
		1112: avpType{"Read-Reply", "Enumerated"},
		1113: avpType{"Sender-Visibility", "Enumerated"},
		1114: avpType{"Service-Key", "UTF8String"},
		1115: avpType{"Billing-Information", "UTF8String"},
		1116: avpType{"Status", "Grouped"},
		1117: avpType{"Status-Code", "UTF8String"},
		1118: avpType{"Status-Text", "UTF8String"},
		1119: avpType{"Routeing-Address-Resolution", "Enumerated"},
		1200: avpType{"Domain-Name", "UTF8String"},
		1201: avpType{"3GPP-Recipient-Address", "Grouped"},
		1202: avpType{"Submission-Time", "Time"},
		1203: avpType{"MM-Content-Type", "Grouped"},
		1204: avpType{"Type-Number", "Enumerated"},
		1205: avpType{"Additional-Type-Information", "UTF8String"},
		1206: avpType{"Content-Size", "Unsigned32"},
		1207: avpType{"Additional-Content-Information", "Grouped"},
		1208: avpType{"Addressee-Type", "Enumerated"},
		1209: avpType{"Priority", "Enumerated"},
		1210: avpType{"Message-ID", "UTF8String"},
		1211: avpType{"Message-Type", "Enumerated"},
		1212: avpType{"Message-Size", "Unsigned32"},
		1213: avpType{"Message-Class", "Grouped"},
		1214: avpType{"Class-Identifier", "Enumerated"},
		1215: avpType{"Token-Text", "UTF8String"},
		1216: avpType{"Delivery-Report-Requested", "Enumerated"},
		1217: avpType{"Adaptations", "Enumerated"},
		1218: avpType{"Applic-ID", "UTF8String"},
		1219: avpType{"Aux-Applic-Info", "UTF8String"},
		1220: avpType{"Content-Class", "Enumerated"},
		1221: avpType{"DRM-Content", "Enumerated"},
		1222: avpType{"Read-Reply-Report-Requested", "Enumerated"},
		1223: avpType{"Reply-Applic-ID", "UTF8String"},
		1224: avpType{"File-Repair-Supported", "Enumerated"},
		1225: avpType{"MBMS-User-Service-Type", "Enumerated"},
		1226: avpType{"Unit-Quota-Threshold", "Unsigned32"},
		1227: avpType{"PDP-Address", "IPAddress"},
		1228: avpType{"SGSN-Address", "IPAddress"},
		1229: avpType{"PoC-Session-Id", "UTF8String"},
		1230: avpType{"Deferred-Location-Event-Type", "UTF8String"},
		1231: avpType{"LCS-APN", "UTF8String"},
		1232: avpType{"LCS-Client-ID", "Grouped"},
		1233: avpType{"LCS-Client-Dialed-By-MS", "UTF8String"},
		1234: avpType{"LCS-Client-External-ID", "UTF8String"},
		1235: avpType{"LCS-Client-Name", "Grouped"},
		1236: avpType{"LCS-Data-Coding-Scheme", "UTF8String"},
		1237: avpType{"LCS-Format-Indicator", "Enumerated"},
		1238: avpType{"LCS-Name-String", "UTF8String"},
		1239: avpType{"LCS-Requestor-ID", "Grouped"},
		1240: avpType{"LCS-Requestor-ID-String", "UTF8String"},
		1241: avpType{"LCS-Client-Type", "Enumerated"},
		1242: avpType{"Location-Estimate", "UTF8String"},
		1243: avpType{"Location-Estimate-Type", "Enumerated"},
		1244: avpType{"Location-Type", "Grouped"},
		1245: avpType{"Positioning-Data", "UTF8String"},
		1246: avpType{"WLAN-Session-Id", "UTF8String"},
		1247: avpType{"PDP-Context-Type", "Enumerated"},
		1248: avpType{"MMBox-Storage-Requested", "Enumerated"},
		1249: avpType{"Service-Specific-Info", "Grouped"},
		1250: avpType{"Called-Asserted-Identity", "UTF8String"},
		1251: avpType{"Requested-Party-Address", "UTF8String"},
		1252: avpType{"PoC-User-Role", "Grouped"},
		1253: avpType{"PoC-User-Role-IDs", "UTF8String"},
		1254: avpType{"PoC-User-Role-info-Units", "Enumerated"},
		1255: avpType{"Talk-Burst-Exchange", "Grouped"},
		1256: avpType{"Service-Generic-Information", "Grouped"},
		1257: avpType{"Service-Specific-Type", "Unsigned32"},
		1258: avpType{"Event-Charging-TimeStamp", "Time"},
		1259: avpType{"Participant-Access-Priority", "Enumerated"},
		1260: avpType{"Participant-Group", "Grouped"},
		1261: avpType{"PoC-Change-Condition", "Enumerated"},
		1262: avpType{"PoC-Change-Time", "Time"},
		1263: avpType{"Access-Network-Information", "UTF8String"},
		1264: avpType{"Trigger", "Grouped"},
		1265: avpType{"Base-Time-Interval", "Unsigned32"},
		1266: avpType{"Envelope", "Grouped"},
		1267: avpType{"Envelope-End-Time", "Time"},
		1268: avpType{"Envelope-Reporting", "Enumerated"},
		1269: avpType{"Envelope-Start-Time", "Time"},
		1270: avpType{"Time-Quota-Mechanism", "Grouped"},
		1271: avpType{"Time-Quota-Type", "Enumerated"},
		1272: avpType{"Early-Media-Description", "Grouped"},
		1273: avpType{"SDP-TimeStamps", "Grouped"},
		1274: avpType{"SDP-Offer-Timestamp", "Time"},
		1275: avpType{"SDP-Answer-Timestamp", "Time"},
		1276: avpType{"AF-Correlation-Information", "Grouped"},
		1277: avpType{"PoC-Session-Initiation-type", "Enumerated"},
		1278: avpType{"Offline-Charging", "Grouped"},
		1279: avpType{"User-Participating-Type", "Enumerated"},
		1280: avpType{"Alternate-Charged-Party-Address", "UTF8String"},
		1281: avpType{"IMS-Communication-Service-Identifier", "UTF8String"},
		1282: avpType{"Number-Of-Received-Talk-Bursts", "Unsigned32"},
		1283: avpType{"Number-Of-Talk-Bursts", "Unsigned32"},
		1284: avpType{"Received-Talk-Burst-Time", "Unsigned32"},
		1285: avpType{"Received-Talk-Burst-Volume", "Unsigned32"},
		1286: avpType{"Talk-Burst-Time", "Unsigned32"},
		1287: avpType{"Talk-Burst-Volume", "Unsigned32"},
		1288: avpType{"Media-Initiator-Party", "UTF8String"},
		1400: avpType{"Subscription-Data", "Grouped"},
		1401: avpType{"Terminal-Information", "Grouped"},
		1402: avpType{"IMEI", "UTF8String"},
		1403: avpType{"Software-Version", "UTF8String"},
		1404: avpType{"QoS-Subscribed", "UTF8String"},
		1405: avpType{"ULR-Flags", "Unsigned32"},
		1406: avpType{"ULA-Flags", "Unsigned32"},
		1407: avpType{"Visited-PLMN-Id", "OctetString"},
		1408: avpType{"Requested-EUTRAN-Authentication-Info", "Grouped"},
		1409: avpType{"Requested-UTRAN-GERAN-Authentication-Info", "Grouped"},
		1410: avpType{"Number-Of-Requested-Vectors", "Unsigned32"},
		1411: avpType{"Re-Synchronization-Info", "OctetString"},
		1412: avpType{"Immediate-Response-Preferred", "Unsigned32"},
		1413: avpType{"Authentication-Info", "Grouped"},
		1414: avpType{"E-UTRAN-Vector", "Grouped"},
		1415: avpType{"UMTS-Vector", "Grouped"},
		1416: avpType{"GERAN-Vector", "Grouped"},
		1417: avpType{"Network-Access-Mode", "Enumerated"},
		1418: avpType{"HPLMN-ODB", "Unsigned32"},
		1419: avpType{"Item-Number", "Unsigned32"},
		1420: avpType{"Cancellation-Type", "Enumerated"},
		1421: avpType{"DSR-Flags", "Unsigned32"},
		1422: avpType{"DSA-Flags", "Unsigned32"},
		1423: avpType{"Context-Identifier", "Unsigned32"},
		1424: avpType{"Subscriber-Status", "Enumerated"},
		1425: avpType{"Operator-Determined-Barring", "Unsigned32"},
		1426: avpType{"Access-Restriction-Data", "Unsigned32"},
		1427: avpType{"APN-OI-Replacement", "UTF8String"},
		1428: avpType{"All-APN-Configurations-Included-Indicator", "Enumerated"},
		1429: avpType{"APN-Configuration-Profile", "Grouped"},
		1430: avpType{"APN-Configuration", "Grouped"},
		1431: avpType{"EPS-Subscribed-QoS-Profile", "Grouped"},
		1432: avpType{"VPLMN-Dynamic-Address-Allowed", "Enumerated"},
		1433: avpType{"STN-SR", "OctetString"},
		1434: avpType{"Alert-Reason", "Enumerated"},
		1435: avpType{"AMBR", "Grouped"},
		1436: avpType{"CSG-Subscription-Data", "Grouped"},
		1437: avpType{"CSG-Id", "Unsigned32"},
		1438: avpType{"PDN-GW-Allocation-Type", "Enumerated"},
		1439: avpType{"Expiration-Date", "Time"},
		1440: avpType{"RAT-Frequency-Selection-Priority-ID", "Unsigned32"},
		1441: avpType{"IDA-Flags", "Unsigned32"},
		1442: avpType{"PUA-Flags", "Unsigned32"},
		1443: avpType{"NOR-Flags", "Unsigned32"},
		1444: avpType{"User-Id", "UTF8String"},
		1445: avpType{"Equipment-Status", "Enumerated"},
		1446: avpType{"Regional-Subscription-Zone-Code", "OctetString"},
		1447: avpType{"RAND", "OctetString"},
		1448: avpType{"XRES", "OctetString"},
		1449: avpType{"AUTN", "OctetString"},
		1450: avpType{"KASME", "OctetString"},
		1452: avpType{"Trace-Collection-Entity", "IPAddress"},
		1453: avpType{"Kc", "OctetString"},
		1454: avpType{"SRES", "OctetString"},
		1455: avpType{"Requesting-Node-Type", "Enumerated"},
		1456: avpType{"PDN-Type", "Enumerated"},
		1457: avpType{"Roaming-Restricted-Due-To-Unsupported-Feature", "Enumerated"},
		1458: avpType{"Trace-Data", "Grouped"},
		1459: avpType{"Trace-Reference", "OctetString"},
		1462: avpType{"Trace-Depth", "Enumerated"},
		1463: avpType{"Trace-NE-Type-List", "OctetString"},
		1464: avpType{"Trace-Interface-List", "OctetString"},
		1465: avpType{"Trace-Event-List", "OctetString"},
		1466: avpType{"OMC-Id", "OctetString"},
		1467: avpType{"GPRS-Subscription-Data", "Grouped"},
		1468: avpType{"Complete-Data-List-Included-Indicator", "Enumerated"},
		1469: avpType{"PDP-Context", "Grouped"},
		1470: avpType{"PDP-Type", "OctetString"},
		1471: avpType{"TGPP2-MEID", "OctetString"},
		1472: avpType{"3GPP-Specific-APN-Info", "Grouped"},
		1473: avpType{"LCS-Info", "Grouped"},
		1474: avpType{"GMLC-Address", "OctetString"},
		1475: avpType{"LCS-PrivacyException", "Grouped"},
		1476: avpType{"SS-Code", "OctetString"},
		1477: avpType{"SS-Status", "OctetString"},
		1478: avpType{"Notification-To-UE-User", "Enumerated"},
		1479: avpType{"External-Client", "Grouped"},
		1480: avpType{"Client-Identity", "OctetString"},
		1481: avpType{"GMLC-Restriction", "Enumerated"},
		1482: avpType{"PLMN-Client", "Enumerated"},
		1483: avpType{"3GPP-Service-Type", "Grouped"},
		1484: avpType{"ServiceTypeIdentity", "Unsigned32"},
		1485: avpType{"MO-LR", "Grouped"},
		1486: avpType{"Teleservice-List", "Grouped"},
		1487: avpType{"TS-Code", "OctetString"},
		1488: avpType{"Call-Barring-Infor-List", "Grouped"},
		1489: avpType{"SGSN-Number", "OctetString"},
		1490: avpType{"IDR-Flags", "Unsigned32"},
		1491: avpType{"ICS-Indicator", "Enumerated"},
		1492: avpType{"IMS-Voice-Over-PSSessions-Supported", "Enumerated"},
		1493: avpType{"Homogeneous-Support-of-IMS-Voice-Over-PS-Sessions", "Enumerated"},
		1494: avpType{"Last-UE-Activity-Time", "Time"},
		1495: avpType{"EPS-User-State", "Grouped"},
		1496: avpType{"EPS-Location-Information", "Grouped"},
		1497: avpType{"MME-User-State", "Grouped"},
		1498: avpType{"SGSN-User-State", "Grouped"},
		1499: avpType{"User-State", "Enumerated"},
		1500: avpType{"Non-3GPP-User-Data", "Grouped"},
		1501: avpType{"Non-3GPP-IP-Access", "Enumerated"},
		1502: avpType{"Non-3GPP-IP-Access-APN", "Enumerated"},
		1503: avpType{"AN-Trusted", "Enumerated"},
		1504: avpType{"ANID", "UTF8String"},
		1505: avpType{"Trace-Info", "Grouped"},
		1506: avpType{"MIP-FA-RK", "OctetString"},
		1507: avpType{"MIP-FA-RK-SPI", "Unsigned32"},
		1600: avpType{"MME-Location-Information", "Grouped"},
		1601: avpType{"SGSN-Location-Information", "Grouped"},
		1602: avpType{"E-UTRAN-Cell-Global-Identity", "OctetString"},
		1603: avpType{"Tracking-Area-Identity", "OctetString"},
		1604: avpType{"Cell-Global-Identity", "OctetString"},
		1605: avpType{"Routing-Area-Identity", "OctetString"},
		1606: avpType{"Location-Area-Identity", "OctetString"},
		1607: avpType{"Service-Area-Identity", "OctetString"},
		1608: avpType{"Geographical-Information", "OctetString"},
		1609: avpType{"Geodetic-Information", "OctetString"},
		2000: avpType{"SMS-Information", "Grouped"},
		2001: avpType{"Data-Coding-Scheme", "Integer32"},
		2002: avpType{"Destination-Interface", "Grouped"},
		2003: avpType{"Interface-Id", "UTF8String"},
		2004: avpType{"Interface-Port", "UTF8String"},
		2005: avpType{"Interface-Text", "UTF8String"},
		2006: avpType{"Interface-Type", "Enumerated"},
		2007: avpType{"SM-Message-Type", "Enumerated"},
		2008: avpType{"Originating-SCCP-Address", "IPAddress"},
		2009: avpType{"Originator-Interface", "Grouped"},
		2010: avpType{"Recipient-SCCP-Address", "IPAddress"},
		2011: avpType{"Reply-Path-Requested", "Enumerated"},
		2012: avpType{"SM-Discharge-Time", "Time"},
		2013: avpType{"SM-Protocol-ID", "OctetString"},
		2014: avpType{"SM-Status", "OctetString"},
		2015: avpType{"SM-User-Data-Header", "OctetString"},
		2016: avpType{"SMS-Node", "Enumerated"},
		2017: avpType{"SMSC-Address", "IPAddress"},
		2018: avpType{"Client-Address", "IPAddress"},
		2019: avpType{"Number-of-Messages-Sent", "Unsigned32"},
		2020: avpType{"Low-Balance-Indication", "Enumerated"},
		2021: avpType{"Remaining-Balance", "Grouped"},
		2022: avpType{"Refund-Information", "OctetString"},
		2023: avpType{"Carrier-Select-Routing-Information", "UTF8String"},
		2024: avpType{"Number-Portability-Routing-Information", "UTF8String"},
		2025: avpType{"PoC-Event-Type", "Enumerated"},
		2026: avpType{"Recipients", "Grouped"},
		2027: avpType{"3GPP-Destination-Interface", "Grouped"},
		2028: avpType{"Recipient-Received-Address", "Grouped"},
		2029: avpType{"SM-Service-Type", "Enumerated"},
		2030: avpType{"MMTel-Information", "Grouped"},
		2031: avpType{"Service-type", "Enumerated"},
		2032: avpType{"Service-Mode", "Enumerated"},
		2033: avpType{"Subscriber-Role", "Enumerated"},
		2034: avpType{"Number-Of-Diversions", "Unsigned32"},
		2035: avpType{"Associated-Party-Address", "UTF8String"},
		2036: avpType{"SDP-Type", "Enumerated"},
		2037: avpType{"Change-Condition", "Integer32"},
		2038: avpType{"Change-Time", "Time"},
		2039: avpType{"Diagnostics", "Time"},
		2040: avpType{"Service-Data-Container", "Grouped"},
		2041: avpType{"Start-Time", "Time"},
		2042: avpType{"Stop-Time", "Time"},
		2043: avpType{"Time-First-Usage", "Time"},
		2044: avpType{"Time-Last-Usage", "Time"},
		2045: avpType{"Time-Usage", "Unsigned32"},
		2046: avpType{"Traffic-Data-Volumes", "Grouped"},
		2047: avpType{"Serving-Node-Type", "Enumerated"},
		2048: avpType{"Supplementary-Service", "Grouped"},
		2049: avpType{"Participant-Action-Type", "Enumerated"},
		2050: avpType{"3GPP-PDN-Connection-ID", "Unsigned32"},
		2051: avpType{"Dynamic-Address-Flag", "Enumerated"},
		2052: avpType{"Accumulated-Cost", "Grouped"},
		2053: avpType{"AoC-Cost-Information", "Grouped"},
		2054: avpType{"AoC-Information", "Grouped"},
		2055: avpType{"AoC-Request-Type", "Enumerated"},
		2056: avpType{"Current-Tariff", "Grouped"},
		2057: avpType{"Next-Tariff", "Grouped"},
		2058: avpType{"Rate-Element", "Grouped"},
		2059: avpType{"Scale-Factor", "Grouped"},
		2060: avpType{"Tariff-Information", "Grouped"},
		2061: avpType{"Unit-Cost", "Grouped"},
		2062: avpType{"Incremental-Cost", "Grouped"},
		2063: avpType{"Local-Sequence-Number", "Unsigned32"},
		2064: avpType{"Node-Id", "UTF8String"},
		2065: avpType{"SGW-Change", "Enumerated"},
		2066: avpType{"Charging-Characteristic-Selection-Mode", "Enumerated"},
		2100: avpType{"Reserved", "OctetString"},
		2101: avpType{"Application-Server-ID", "Unsigned32"},
		2102: avpType{"Application-Service-Type", "Enumerated"},
		2103: avpType{"Application-Session-ID", "Unsigned32"},
		2104: avpType{"Delivery-Status", "UTF8String"},
		2105: avpType{"Reserved", "OctetString"},
		2106: avpType{"Reserved", "OctetString"},
		2107: avpType{"Reserved", "OctetString"},
		2108: avpType{"Reserved", "OctetString"},
		2109: avpType{"Reserved", "OctetString"},
		2110: avpType{"IM-Information", "Grouped"},
		2111: avpType{"Number-Of-Messages-Successfully-Exploded", "Unsigned32"},
		2112: avpType{"Number-Of-Messages-Successfully-Sent", "Unsigned32"},
		2113: avpType{"Total-Number-Of-Messages-Exploded", "Unsigned32"},
		2114: avpType{"Total-Number-Of-Messages-Sen", "Unsigned32"},
		2300: avpType{"Reserved", "OctetString"},
		2301: avpType{"SIP-Request-Timestamp-Fraction", "Unsigned32"},
		2302: avpType{"SIP-Response-Timestamp-Fraction", "Unsigned32"},
		2303: avpType{"Online-Charging-Flag", "Enumerated"},
		2304: avpType{"CUG-Information", "OctetString"},
		2305: avpType{"Real-Time-Tariff-Information", "Grouped"},
		2306: avpType{"Tariff-XML", "UTF8String"},
		2307: avpType{"MBMS-GW-Address", "IPAddress"},
		2308: avpType{"IMSI-Unauthenticated-Flag", "Enumerated"},
		2500: avpType{"3GPP-Location-Type", "Enumerated"},
		2501: avpType{"LCS-EPS-Client-Name", "Grouped"},
		2502: avpType{"LCS-Requestor-Name", "Grouped"},
		2503: avpType{"LCS-Priority", "Unsigned32"},
		2504: avpType{"LCS-QoS", "Grouped"},
		2508: avpType{"Velocity-Requested", "Enumerated"},
		2510: avpType{"3GPP-Supported-GAD-Shapes", "Unsigned32"},
		2511: avpType{"LCS-Codeword", "UTF8String"},
		2512: avpType{"LCS-Privacy-Check", "Enumerated"},
		2514: avpType{"Age-Of-Location-Estimate", "Unsigned32"},
		2517: avpType{"ECGI", "OctetString"},
		2520: avpType{"LCS-Service-Type-ID", "Unsigned32"},
		2521: avpType{"LCS-Privacy-Check-Non-Session", "Grouped"},
		2522: avpType{"LCS-Privacy-Check-Session", "Grouped"},
		2523: avpType{"LCS-QoS-Class", "Enumerated"},
	},
	9: {
		131072: avpType{"Cisco-Charging-Rule-Definition", "Grouped"},
		131073: avpType{"Content-Definition", "Grouped"},
		131074: avpType{"Billing-Policy-Definition", "Grouped"},
		131075: avpType{"Policy-Map-Definition", "Grouped"},
		131076: avpType{"Service-Definition", "Grouped"},
		131077: avpType{"Content-Policy-Map", "Grouped"},
		131078: avpType{"Service-Info", "Grouped"},
		131079: avpType{"Billing-Plan-Definition", "Grouped"},
		131080: avpType{"Volume-Threshold", "Unsigned32"},
		131081: avpType{"Time-Threshold", "Unsigned32"},
		131082: avpType{"Content-Idle-Timer", "Unsigned32"},
		131083: avpType{"Nexthop-Uplink", "IPAddress"},
		131084: avpType{"Nexthop-Downlink", "IPAddress"},
		131085: avpType{"L7-Parse-Protocol-Type", "Unsigned32"},
		131086: avpType{"Service-Status", "Grouped"},
		131087: avpType{"Service-Name", "OctetString"},
		131088: avpType{"Biling-Policy-Name", "OctetString"},
		131089: avpType{"Policy-Map-Name", "OctetString"},
		131090: avpType{"Policy-Map-Match", "Grouped"},
		131091: avpType{"Match-String", "UTF8String"},
		131092: avpType{"Attribute-String", "UTF8String"},
		131093: avpType{"Online-Billing-Basis", "Unsigned32"},
		131094: avpType{"Service-Activation", "Unsigned32"},
		131095: avpType{"CDR-Volume-Threshold", "Unsigned32"},
		131096: avpType{"CDR-Time-Threshold", "Unsigned32"},
		131097: avpType{"Advice-Of-Charge", "Grouped"},
		131098: avpType{"Append-URL", "Unsigned32"},
		131099: avpType{"Cisco-Confirm-Token", "OctetString"},
		131100: avpType{"Cisco-Service-Class", "Unsigned32"},
		131101: avpType{"Service-Idle-Time", "Unsigned32"},
		131102: avpType{"Owner-Id", "OctetString"},
		131103: avpType{"Owner-Name", "OctetString"},
		131104: avpType{"Online-Passthrough-Quota", "Unsigned32"},
		131105: avpType{"Online-Reauthorization-Threshold", "Unsigned32"},
		131106: avpType{"Online-Reauthorization-Timeout", "Grouped"},
		131107: avpType{"Initial-Timeout", "Unsigned32"},
		131108: avpType{"Maximum-Timeout", "Unsigned32"},
		131109: avpType{"Refund-policy", "OctetString"},
		131110: avpType{"Meter-Exclude", "Unsigned32"},
		131111: avpType{"Meter-Include-Imap", "Unsigned32"},
		131112: avpType{"Metering-Granularity", "Grouped"},
		131113: avpType{"Meter-Increment", "Unsigned32"},
		131114: avpType{"Meter-Initial", "Unsigned32"},
		131115: avpType{"Meter-Minimum", "Unsigned32"},
		131116: avpType{"Verify", "Grouped"},
		131117: avpType{"Cisco-Confirm-Token2", "OctetString"},
		131118: avpType{"Weight", "Unsigned32"},
		131119: avpType{"User-Idle-Timer", "Unsigned32"},
		131120: avpType{"Policy-Preload-Req-Type", "Unsigned32"},
		131121: avpType{"Policy-Preload-Object-Type", "Unsigned32"},
		131122: avpType{"Policy-Preload-Status", "Unsigned32"},
		131123: avpType{"Charging-Rule-Trigger-Type", "Unsigned32"},
		131124: avpType{"Charging-Rule-Event", "Grouped"},
		131125: avpType{"Service-Reporting-Level", "Unsigned32"},
		131126: avpType{"Accounting", "Grouped"},
		131127: avpType{"Accounting-Customer-String", "OctetString"},
		131128: avpType{"L7-Parse-Length", "Unsigned32"},
		131129: avpType{"Service-CDR-Threshold", "Grouped"},
		131130: avpType{"Intermediate-CDR-Threshold", "Grouped"},
		131131: avpType{"CDR-Generation-Delay", "Unsigned32"},
		131132: avpType{"Replicate-Session", "Grouped"},
		131133: avpType{"Replicate-Session-Delay", "Unsigned32"},
		131134: avpType{"Content-Pending-Timer", "Unsigned32"},
		131135: avpType{"Operation-Status", "Unsigned32"},
		131136: avpType{"Subscriber-IP-Source", "Unsigned32"},
		131137: avpType{"Nexthop", "IPAddress"},
		131138: avpType{"Nexthop-Reverse", "IPAddress"},
		131139: avpType{"Charging-Rule-Event-Trigger", "Grouped"},
		131140: avpType{"Billing-Plan-Name", "OctetString"},
		131141: avpType{"Content-Flow-Description", "Grouped"},
		131142: avpType{"Content-Flow-Filter", "Grouped"},
		131143: avpType{"Client-Group-Id", "Grouped"},
		131144: avpType{"ACL-Number", "Unsigned32"},
		131145: avpType{"ACL-Name", "OctetString"},
		131146: avpType{"Destination-IP-Address", "IPAddress"},
		131147: avpType{"Destination-Mask", "IPAddress"},
		131148: avpType{"Protocol-ID", "Unsigned32"},
		131149: avpType{"Start-of-Port-Range", "Unsigned32"},
		131150: avpType{"End-of-Port-Range", "Unsigned32"},
		131151: avpType{"Content-Name", "OctetString"},
		131152: avpType{"Failed-Preload-Object", "Grouped"},
		131153: avpType{"VRF-Name", "OctetString"},
		131154: avpType{"VLAN-Id", "Unsigned32"},
		131155: avpType{"Volume-Usage", "Unsigned64"},
		131156: avpType{"Cisco-Time-Usage", "Grouped"},
		131157: avpType{"Duration", "Unsigned32"},
		131158: avpType{"First-Packet-Timestanp", "Unsigned32"},
		131159: avpType{"Last-Packet-Timestanp", "Unsigned32"},
		131160: avpType{"Cisco-Flow-Description", "Grouped"},
		131161: avpType{"Terminate-Bearer", "Grouped"},
		131162: avpType{"Service-Rating-Group", "Unsigned32"},
		131163: avpType{"Content-Scope", "Unsigned32"},
		131164: avpType{"Flow-Status-Policy-Mismatch", "Unsigned32"},
		131165: avpType{"Policy-Map-Type", "Unsigned32"},
		131166: avpType{"Policy-Map-Match-Install", "Grouped"},
		131167: avpType{"Policy-Map-Match-Remove", "Grouped"},
		131168: avpType{"Policy-Map-Replace", "Unsigned32"},
		131169: avpType{"Cisco-Flow-Status", "Unsigned32"},
		131170: avpType{"Service-QoS", "Grouped"},
		131171: avpType{"QoS-Rate-Limit-UL", "Grouped"},
		131172: avpType{"QoS-Rate-Limit-DL", "Grouped"},
		131173: avpType{"QoS-Rate-Limit", "Grouped"},
		131174: avpType{"Max-Bandwidth", "Unsigned32"},
		131175: avpType{"Rate-Limit-Conform-Action", "Grouped"},
		131176: avpType{"Rate-Limit-Exceed-Action", "Grouped"},
		131177: avpType{"Rate-Limit-Action", "Unsigned32"},
		131178: avpType{"DSCP", "Unsigned32"},
		131179: avpType{"Policy-Map-Install", "Grouped"},
		131180: avpType{"Policy-Map-Remove", "Grouped"},
		131181: avpType{"Billing-Policy-Install", "Grouped"},
		131182: avpType{"Billing-Policy-Remove", "Grouped"},
		131183: avpType{"Content-Install", "Grouped"},
		131184: avpType{"Content-Remove", "Grouped"},
		131185: avpType{"Service-Install", "Grouped"},
		131186: avpType{"Service-Remove", "Grouped"},
		131187: avpType{"Billing-Plan-Install", "Grouped"},
		131188: avpType{"Billing-Plan-Remove", "Grouped"},
		131189: avpType{"Policy-Preload-Error-Code", "Unsigned32"},
		131190: avpType{"Max-Burst-Size", "Unsigned32"},
		131191: avpType{"Failed-Preload-Obj-Name", "Grouped"},
		131192: avpType{"Cisco-Event-Trigger-Type", "Unsigned32"},
		131193: avpType{"Cisco-Event-Trigger", "Grouped"},
		131194: avpType{"TCP-SYN", "OctetString"},
		131195: avpType{"Cisco-Event", "Grouped"},
		131196: avpType{"Interleaved", "Unsigned32"},
		131197: avpType{"Control-URL", "Grouped"},
		131198: avpType{"Relative-URL", "Unsigned32"},
		131199: avpType{"Mining", "Unsigned32"},
		131200: avpType{"User-Default", "Unsigned32"},
		131201: avpType{"Cisco-Priority", "Unsigned32"},
		131202: avpType{"Domain-Group-Name", "OctetString"},
		131203: avpType{"Domain-Group-Definition", "Grouped"},
		131204: avpType{"Domain-Group-Install", "Grouped"},
		131205: avpType{"Domain-Group-Remove", "Grouped"},
		131206: avpType{"Domain-Group-Activation", "Unsigned32"},
		131207: avpType{"Dual-Billing-Basis", "Unsigned32"},
		131208: avpType{"Dual-Passthrough-Quota", "Unsigned32"},
		131209: avpType{"Dual-Reauthorization-Threshold", "Unsigned32"},
		131210: avpType{"Virtual-Online", "Unsigned32"},
		131211: avpType{"Nexthop-Media", "IPAddress"},
		131212: avpType{"Nexthop-Override", "Unsigned32"},
		131213: avpType{"Cisco-Quota-Consumption-Time", "Unsigned32"},
		131214: avpType{"Class-Map-Name", "UTF8String"},
		131215: avpType{"Header-Group-Name", "UTF8String"},
		131216: avpType{"Header-Group-Definition", "Grouped"},
		131217: avpType{"Header-Group-Install", "Grouped"},
		131218: avpType{"Header-Group-Remove", "Grouped"},
		131219: avpType{"Header-Insert-Name", "UTF8String"},
		131220: avpType{"Header-Field-Name", "UTF8String"},
		131221: avpType{"Header-Class-Name", "UTF8String"},
		131222: avpType{"Header-Class-Mode", "Unsigned32"},
		131223: avpType{"Header-Class", "Grouped"},
		131224: avpType{"Radius-Attribute-Type", "Unsigned32"},
		131225: avpType{"Radius-Vsa-Vendor-Id", "Unsigned32"},
		131226: avpType{"Radius-Vsa-Subattribute-Type", "Unsigned32"},
		131227: avpType{"Header-Item-Radius", "Grouped"},
		131228: avpType{"Header-Item", "Unsigned32"},
		131229: avpType{"Header-Item-String", "UTF8String"},
		131230: avpType{"Header-Items-Encrypted", "Grouped"},
		131231: avpType{"Header-Insert-Definition", "Grouped"},
		131232: avpType{"Header-Insert-Install", "Grouped"},
		131233: avpType{"Header-Insert-Remove", "Grouped"},
		131234: avpType{"User-Idle-Pod", "Unsigned32"},
		131235: avpType{"Domain-Group-Clear", "Unsigned32"},
		131236: avpType{"Cisco-QoS-Profile-Name", "UTF8String"},
		131237: avpType{"Cisco-QoS-Profile", "Grouped"},
		131238: avpType{"Cisco-QoS-Profile-Install", "Grouped"},
		131239: avpType{"Cisco-QoS-Profile-Remove", "Grouped"},
		131240: avpType{"Cisco-QoS-Profile-Uplink", "Grouped"},
		131241: avpType{"Cisco-QoS-Profile-Downlink", "Grouped"},
		131242: avpType{"Header-Item-Encryption", "Unsigned32"},
		131243: avpType{"Service-Group-Name", "OctetString"},
		131244: avpType{"Service-Group-Definition", "Grouped"},
		131245: avpType{"Service-Group-Install", "Grouped"},
		131246: avpType{"Service-Group-Remove", "Grouped"},
		131247: avpType{"Service-Group-Event", "Grouped"},
		131248: avpType{"Cisco-Report-Usage", "Grouped"},
		131249: avpType{"Accel", "Unsigned32"},
		131250: avpType{"Cisco-Answer-User-Usage", "Grouped"},
		131251: avpType{"Cisco-Request-Usage-Type", "Unsigned32"},
		131252: avpType{"Cisco-Request-Charging-Rule-Usage", "Grouped"},
		131253: avpType{"Cisco-Request-Service-Group-Usage", "Grouped"},
		131254: avpType{"Cisco-Answer-Charging-Rule-Usage", "Grouped"},
		131255: avpType{"Cisco-Answer-Service-Group-Usage", "Grouped"},
		131256: avpType{"User-Agent", "OctetString"},
		131257: avpType{"Service-Life-Time", "Unsigned32"},
		131258: avpType{"Volume-Threshold-64", "Unsigned64"},
	},
	12645: {
		261: avpType{"VDF-Reporting-Reason", "Unsigned32"},
		256: avpType{"VDF-Context-Type", "Unsigned32"},
		257: avpType{"VDF-Quota-Consumption-Time", "Unsigned32"},
		258: avpType{"VDF-Quota-Holding-Time", "Unsigned32"},
		259: avpType{"VDF-Time-Quota-Threshold", "Unsigned32"},
		260: avpType{"VDF-Radio-Access-Technology", "Unsigned32"},
		262: avpType{"VDF-Rulebase-Id", "UTF8String"},
		263: avpType{"VDF-Time-Of-First-Usage", "Time"},
		264: avpType{"VDF-Time-Of-Last-Usage", "Time"},
		265: avpType{"VDF-Trigger", "Grouped"},
		266: avpType{"VDF-Trigger-Type", "Unsigned32"},
		267: avpType{"VDF-User-Location-Information", "OctetString"},
		268: avpType{"VDF-Volume-Quota-Threshold", "Unsigned32"},
	},
	193: {
		290:  avpType{"Rule-Space-Suggestion", "UTF8String"},
		291:  avpType{"Rule-Space-Decision", "UTF8String"},
		292:  avpType{"Bearer-Control-Options", "Unsigned32"},
		293:  avpType{"Bearer-Control-Reject", "Unsigned32"},
		294:  avpType{"ARP", "Unsigned32"},
		1146: avpType{"Customer-Id", "UTF8String"},
	},
	13019: {
		298: avpType{"ETSI-Experimental-Result-Code", "Unsigned32"},
		299: avpType{"Not defined in .xml", "OctetString"},
		308: avpType{"Maximum-Allowed-Bandwidth-UL", "Unsigned32"},
		320: avpType{"Not defined in .xml", "OctetString"},
		321: avpType{"Not defined in .xml", "OctetString"},
		322: avpType{"Not defined in .xml", "OctetString"},
		323: avpType{"Not defined in .xml", "OctetString"},
		324: avpType{"Not defined in .xml", "OctetString"},
		325: avpType{"Not defined in .xml", "OctetString"},
		326: avpType{"Not defined in .xml", "OctetString"},
		327: avpType{"Not defined in .xml", "OctetString"},
		328: avpType{"Not defined in .xml", "OctetString"},
		329: avpType{"Not defined in .xml", "OctetString"},
		330: avpType{"Not defined in .xml", "OctetString"},
		331: avpType{"Not defined in .xml", "OctetString"},
		332: avpType{"Not defined in .xml", "OctetString"},
		333: avpType{"Not defined in .xml", "OctetString"},
		334: avpType{"Not defined in .xml", "OctetString"},
		335: avpType{"Not defined in .xml", "OctetString"},
		336: avpType{"Not defined in .xml", "OctetString"},
		337: avpType{"Not defined in .xml", "OctetString"},
		338: avpType{"Not defined in .xml", "OctetString"},
		339: avpType{"Not defined in .xml", "OctetString"},
		340: avpType{"Not defined in .xml", "OctetString"},
		341: avpType{"Not defined in .xml", "OctetString"},
		342: avpType{"Not defined in .xml", "OctetString"},
		343: avpType{"Not defined in .xml", "OctetString"},
		344: avpType{"Not defined in .xml", "OctetString"},
		345: avpType{"Not defined in .xml", "OctetString"},
		346: avpType{"Not defined in .xml", "OctetString"},
		347: avpType{"Not defined in .xml", "OctetString"},
		348: avpType{"Not defined in .xml", "OctetString"},
		349: avpType{"Not defined in .xml", "OctetString"},
		350: avpType{"ETSI-Location-Information", "Grouped"},
		351: avpType{"RACS-Contact-Point", "DiameterIdentity"},
		352: avpType{"Terminal-Type", "OctetString"},
		353: avpType{"ETSI-Requested-Information", "Enumerated"},
		354: avpType{"ETSI-Event-Type", "Enumerated"},
		355: avpType{"Civic-Location", "OctetString"},
		356: avpType{"Geospatial-Location", "OctetString"},
		357: avpType{"Not defined in .xml", "OctetString"},
		358: avpType{"Not defined in .xml", "OctetString"},
		359: avpType{"Not defined in .xml", "OctetString"},
		360: avpType{"Not defined in .xml", "OctetString"},
		361: avpType{"Not defined in .xml", "OctetString"},
		362: avpType{"Not defined in .xml", "OctetString"},
		363: avpType{"Not defined in .xml", "OctetString"},
		364: avpType{"Not defined in .xml", "OctetString"},
		365: avpType{"Not defined in .xml", "OctetString"},
		366: avpType{"Not defined in .xml", "OctetString"},
		367: avpType{"Not defined in .xml", "OctetString"},
		368: avpType{"Not defined in .xml", "OctetString"},
		369: avpType{"Not defined in .xml", "OctetString"},
		370: avpType{"Not defined in .xml", "OctetString"},
		371: avpType{"Not defined in .xml", "OctetString"},
		372: avpType{"Not defined in .xml", "OctetString"},
		373: avpType{"Not defined in .xml", "OctetString"},
		374: avpType{"Not defined in .xml", "OctetString"},
		375: avpType{"Not defined in .xml", "OctetString"},
		376: avpType{"Not defined in .xml", "OctetString"},
		377: avpType{"Not defined in .xml", "OctetString"},
		379: avpType{"Not defined in .xml", "OctetString"},
		380: avpType{"Not defined in .xml", "OctetString"},
		381: avpType{"Not defined in .xml", "OctetString"},
		382: avpType{"Not defined in .xml", "OctetString"},
		383: avpType{"Not defined in .xml", "OctetString"},
		384: avpType{"Not defined in .xml", "OctetString"},
		385: avpType{"Not defined in .xml", "OctetString"},
		386: avpType{"Not defined in .xml", "OctetString"},
		387: avpType{"Not defined in .xml", "OctetString"},
		388: avpType{"Not defined in .xml", "OctetString"},
		389: avpType{"Not defined in .xml", "OctetString"},
		390: avpType{"Not defined in .xml", "OctetString"},
		391: avpType{"Not defined in .xml", "OctetString"},
		392: avpType{"Not defined in .xml", "OctetString"},
		393: avpType{"Not defined in .xml", "OctetString"},
		394: avpType{"Not defined in .xml", "OctetString"},
		395: avpType{"Not defined in .xml", "OctetString"},
		396: avpType{"Not defined in .xml", "OctetString"},
		397: avpType{"Not defined in .xml", "OctetString"},
		398: avpType{"Not defined in .xml", "OctetString"},
		399: avpType{"Not defined in .xml", "OctetString"},
		421: avpType{"Not defined in .xml", "OctetString"},
		422: avpType{"Not defined in .xml", "OctetString"},
		423: avpType{"Not defined in .xml", "OctetString"},
		424: avpType{"Not defined in .xml", "OctetString"},
		425: avpType{"Not defined in .xml", "OctetString"},
		426: avpType{"Not defined in .xml", "OctetString"},
		427: avpType{"Not defined in .xml", "OctetString"},
		428: avpType{"Not defined in .xml", "OctetString"},
		429: avpType{"Not defined in .xml", "OctetString"},
		430: avpType{"Not defined in .xml", "OctetString"},
		431: avpType{"Not defined in .xml", "OctetString"},
		432: avpType{"Not defined in .xml", "OctetString"},
		433: avpType{"Not defined in .xml", "OctetString"},
		434: avpType{"Not defined in .xml", "OctetString"},
		435: avpType{"Not defined in .xml", "OctetString"},
		436: avpType{"Not defined in .xml", "OctetString"},
		437: avpType{"Not defined in .xml", "OctetString"},
		438: avpType{"Not defined in .xml", "OctetString"},
		439: avpType{"Not defined in .xml", "OctetString"},
		440: avpType{"Not defined in .xml", "OctetString"},
		441: avpType{"Not defined in .xml", "OctetString"},
		442: avpType{"Not defined in .xml", "OctetString"},
		443: avpType{"Not defined in .xml", "OctetString"},
		444: avpType{"Not defined in .xml", "OctetString"},
		445: avpType{"Not defined in .xml", "OctetString"},
		446: avpType{"Not defined in .xml", "OctetString"},
		447: avpType{"Not defined in .xml", "OctetString"},
		448: avpType{"Not defined in .xml", "OctetString"},
		449: avpType{"Not defined in .xml", "OctetString"},
		450: avpType{"Binding-information", "Grouped"},
		451: avpType{"Binding-Input-List", "Grouped"},
		452: avpType{"Binding-Output-List", "Grouped"},
		453: avpType{"V6-Transport-address", "Grouped"},
		454: avpType{"V4-Transport-Address", "Grouped"},
		455: avpType{"Port-Number", "Unsigned32"},
		456: avpType{"Reservation-Class", "Unsigned32"},
		457: avpType{"Requested-Information", "Enumerated"},
		458: avpType{"Reservation-Priority", "Enumerated"},
		459: avpType{"ETSI-Service-Class", "UTF8String"},
		460: avpType{"Not defined in .xml", "OctetString"},
		461: avpType{"Not defined in .xml", "OctetString"},
		462: avpType{"Not defined in .xml", "OctetString"},
		463: avpType{"Not defined in .xml", "OctetString"},
		464: avpType{"Not defined in .xml", "OctetString"},
		465: avpType{"Not defined in .xml", "OctetString"},
		466: avpType{"Not defined in .xml", "OctetString"},
		467: avpType{"Not defined in .xml", "OctetString"},
		468: avpType{"Not defined in .xml", "OctetString"},
		469: avpType{"Not defined in .xml", "OctetString"},
		470: avpType{"Not defined in .xml", "OctetString"},
		471: avpType{"Not defined in .xml", "OctetString"},
		472: avpType{"Not defined in .xml", "OctetString"},
		473: avpType{"Not defined in .xml", "OctetString"},
		474: avpType{"Not defined in .xml", "OctetString"},
		475: avpType{"Not defined in .xml", "OctetString"},
		476: avpType{"Not defined in .xml", "OctetString"},
		477: avpType{"Not defined in .xml", "OctetString"},
		478: avpType{"Not defined in .xml", "OctetString"},
		479: avpType{"Not defined in .xml", "OctetString"},
		480: avpType{"Not defined in .xml", "OctetString"},
		481: avpType{"Not defined in .xml", "OctetString"},
		482: avpType{"Not defined in .xml", "OctetString"},
		483: avpType{"Not defined in .xml", "OctetString"},
		484: avpType{"Not defined in .xml", "OctetString"},
		485: avpType{"Not defined in .xml", "OctetString"},
		486: avpType{"Not defined in .xml", "OctetString"},
		487: avpType{"Not defined in .xml", "OctetString"},
		488: avpType{"Not defined in .xml", "OctetString"},
		489: avpType{"Not defined in .xml", "OctetString"},
		490: avpType{"Not defined in .xml", "OctetString"},
		491: avpType{"Not defined in .xml", "OctetString"},
		492: avpType{"Not defined in .xml", "OctetString"},
		493: avpType{"Not defined in .xml", "OctetString"},
		494: avpType{"Not defined in .xml", "OctetString"},
		495: avpType{"Not defined in .xml", "OctetString"},
		496: avpType{"Not defined in .xml", "OctetString"},
		497: avpType{"Not defined in .xml", "OctetString"},
		498: avpType{"Not defined in .xml", "OctetString"},
		499: avpType{"Not defined in .xml", "OctetString"},
		514: avpType{"ETSI-Digest-URI", "UTF8String"},
	},
	14008: {
		100: avpType{"GIADDR", "UTF8String"},
		101: avpType{"UACS-Accounting", "UTF8String"},
	},
	5535: {
		1000: avpType{"3GPP2-Bearer-Usage", "Enumerated"},
		1001: avpType{"3GPP2-Charging-Rule-Install", "Grouped"},
		1002: avpType{"3GPP2-Charging-Rule-Remove", "Grouped"},
		1003: avpType{"3GPP2-Charging-Rule-Definition", "Grouped"},
		1004: avpType{"3GPP2-Charging-Rule-Base-Name", "OctetString"},
		1005: avpType{"3GPP2-Charging-Rule-Name", "OctetString"},
		1006: avpType{"3GPP2-Event-Trigger", "Enumerated"},
		1007: avpType{"3GPP2-Metering-Method", "Enumerated"},
		1008: avpType{"3GPP2-Offline", "Enumerated"},
		1009: avpType{"3GPP2-Online", "Enumerated"},
		1010: avpType{"3GPP2-Precedence", "Unsigned32"},
		1011: avpType{"Primary-CCF-Address", "DiameterURI"},
		1012: avpType{"Primary-OCS-Address", "DiameterURI"},
		1014: avpType{"3GPP2-Reporting-Level", "Enumerated"},
		1015: avpType{"Secondary-CCF-Address", "DiameterURI"},
		1016: avpType{"Secondary-OCS-Address", "DiameterURI"},
		1018: avpType{"3GPP2-TFT-Packet-Filter-Information", "Grouped"},
		1019: avpType{"3GPP2-ToS-Traffic-Class", "OctetString"},
		1017: avpType{"3GPP2-TFT-Filter", "IPFilterRule"},
		6071: avpType{"3GPP2-Correlation-Id", "OctetString"},
		6074: avpType{"3GPP2-RP-Session-ID", "OctetString"},
		6073: avpType{"3GPP2-Serving-PCF", "Address"},
		6075: avpType{"3GPP2-User-Zone", "OctetString"},
		6077: avpType{"3GPP2-Information", "Grouped"},
		6078: avpType{"Subscriber-Priority", "Grouped"},
		6079: avpType{"Auth-Profile-Id-Forward", "Unsigned32"},
		6080: avpType{"Auth-Profile-Id-Reverse", "Unsigned32"},
		6081: avpType{"Auth-Profile-Id-Bi-Direction", "Unsigned32"},
		6082: avpType{"3GPP2-Max-Inst-Per-Service-Option", "Unsigned32"},
		6083: avpType{"3GPP2-Allowed-Persistent-TFTs", "Unsigned32"},
		6084: avpType{"3GPP2-Max-Svc-Inst-Link-Flow-Total", "Unsigned32"},
		6085: avpType{"3GPP2-Service-Option-Profile", "Grouped"},
		6086: avpType{"3GPP2-Service-Option", "Unsigned32"},
		6087: avpType{"3GPP2-Max-Auth-Aggr-BW-BET", "Unsigned32"},
		6088: avpType{"3GPP2-Max-Per-Flow-Priority-User", "Unsigned32"},
		6089: avpType{"3GPP2-Inter-User-Priority", "Unsigned32"},
		9010: avpType{"3GPP2-BSID", "UTF8String"},
	},
	29168: {
		102: avpType{"TMO-Validity-Time", "Grouped"},
		103: avpType{"TMO-Activation-Time", "UTF8String"},
		104: avpType{"TMO-Deactivation-Time", "UTF8String"},
		105: avpType{"TMO-Activation-Day", "UTF8String"},
		106: avpType{"TMO-Deactivation-Day", "UTF8String"},
		107: avpType{"TMO-Activity-Timer", "Unsigned32"},
		108: avpType{"TMO-QoS-Information-Definition", "Grouped"},
		109: avpType{"TMO-Disable-Policing", "Enumerated"},
		110: avpType{"TMO-Update-Bearer-QoS", "Enumerated"},
		111: avpType{"TMO-Redirect-Server", "Grouped"},
		112: avpType{"TMO-Redirect-Address-Type", "Enumerated"},
		113: avpType{"TMO-Redirect-Server-Address", "UTF8String"},
		114: avpType{"TMO-Append-Original-URL", "Enumerated"},
		115: avpType{"TMO-Deactivate-By-Redirect", "Enumerated"},
		116: avpType{"TMO-L7-Protocol-Group", "UTF8String"},
		117: avpType{"TMO-L7-Definition", "Grouped"},
		118: avpType{"TMO-L7-Protocol", "UTF8String"},
		119: avpType{"TMO-L7-Content-Type", "UTF8String"},
		120: avpType{"TMO-L7-URL", "UTF8String"},
		121: avpType{"TMO-L7-Method", "UTF8String"},
		122: avpType{"TMO-L7-User-Agent", "UTF8String"},
		123: avpType{"TMO-L7-Charging-Rule-Remove", "Grouped"},
	},
}
